// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module addsub_2 (
        ap_ready,
        a_V,
        b_V,
        add_V,
        ap_return
);


output   ap_ready;
input  [39:0] a_V;
input  [39:0] b_V;
input  [0:0] add_V;
output  [40:0] ap_return;

wire  signed [40:0] lhs_V_fu_34_p1;
wire   [40:0] rhs_V_fu_38_p1;
wire   [40:0] ret_V_fu_48_p2;
wire   [40:0] ret_V_4_fu_42_p2;

assign ap_ready = 1'b1;

assign ap_return = ((add_V[0:0] === 1'b1) ? ret_V_fu_48_p2 : ret_V_4_fu_42_p2);

assign lhs_V_fu_34_p1 = $signed(a_V);

assign ret_V_4_fu_42_p2 = ($signed(lhs_V_fu_34_p1) - $signed(rhs_V_fu_38_p1));

assign ret_V_fu_48_p2 = ($signed(lhs_V_fu_34_p1) + $signed(rhs_V_fu_38_p1));

assign rhs_V_fu_38_p1 = b_V;

endmodule //addsub_2
