// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Erode (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_src_rows_V_dout,
        p_src_rows_V_empty_n,
        p_src_rows_V_read,
        p_src_cols_V_dout,
        p_src_cols_V_empty_n,
        p_src_cols_V_read,
        p_src_data_stream_V_dout,
        p_src_data_stream_V_empty_n,
        p_src_data_stream_V_read,
        p_dst_data_stream_V_din,
        p_dst_data_stream_V_full_n,
        p_dst_data_stream_V_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state9 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] p_src_rows_V_dout;
input   p_src_rows_V_empty_n;
output   p_src_rows_V_read;
input  [31:0] p_src_cols_V_dout;
input   p_src_cols_V_empty_n;
output   p_src_cols_V_read;
input  [7:0] p_src_data_stream_V_dout;
input   p_src_data_stream_V_empty_n;
output   p_src_data_stream_V_read;
output  [7:0] p_dst_data_stream_V_din;
input   p_dst_data_stream_V_full_n;
output   p_dst_data_stream_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_rows_V_read;
reg p_src_cols_V_read;
reg p_src_data_stream_V_read;
reg p_dst_data_stream_V_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_src_rows_V_blk_n;
reg    p_src_cols_V_blk_n;
reg    p_src_data_stream_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] and_ln118_3_reg_1091;
reg   [0:0] icmp_ln899_reg_1047;
reg   [0:0] icmp_ln887_reg_1038;
reg    p_dst_data_stream_V_blk_n;
reg    ap_enable_reg_pp0_iter5;
reg   [0:0] and_ln512_reg_1108;
reg   [0:0] and_ln512_reg_1108_pp0_iter4_reg;
reg   [31:0] t_V_6_reg_261;
reg   [31:0] stop_row_reg_989;
reg    ap_block_state1;
reg   [31:0] cols_reg_998;
wire   [31:0] add_ln443_fu_272_p2;
reg   [31:0] add_ln443_reg_1003;
wire   [31:0] add_ln443_1_fu_278_p2;
reg   [31:0] add_ln443_1_reg_1008;
wire   [31:0] add_ln458_fu_284_p2;
reg   [31:0] add_ln458_reg_1013;
wire   [31:0] add_ln506_fu_290_p2;
reg   [31:0] add_ln506_reg_1019;
wire   [0:0] icmp_ln443_fu_296_p2;
wire    ap_CS_fsm_state2;
wire   [31:0] i_V_fu_301_p2;
reg   [31:0] i_V_reg_1033;
wire   [0:0] icmp_ln887_fu_307_p2;
wire   [0:0] xor_ln457_fu_312_p2;
reg   [0:0] xor_ln457_reg_1042;
wire   [0:0] icmp_ln899_fu_328_p2;
wire   [0:0] icmp_ln879_fu_334_p2;
reg   [0:0] icmp_ln879_reg_1052;
wire   [0:0] icmp_ln879_1_fu_340_p2;
reg   [0:0] icmp_ln879_1_reg_1056;
wire   [0:0] icmp_ln899_1_fu_346_p2;
reg   [0:0] icmp_ln899_1_reg_1060;
wire   [1:0] trunc_ln493_fu_502_p1;
reg   [1:0] trunc_ln493_reg_1067;
wire   [1:0] trunc_ln493_1_fu_519_p1;
reg   [1:0] trunc_ln493_1_reg_1072;
wire   [1:0] trunc_ln493_2_fu_536_p1;
reg   [1:0] trunc_ln493_2_reg_1077;
wire   [0:0] icmp_ln444_fu_540_p2;
reg   [0:0] icmp_ln444_reg_1082;
wire    ap_block_state3_pp0_stage0_iter0;
reg    ap_predicate_op114_read_state4;
reg    ap_predicate_op120_read_state4;
reg    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state6_pp0_stage0_iter3;
wire    ap_block_state7_pp0_stage0_iter4;
reg    ap_block_state8_pp0_stage0_iter5;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln444_reg_1082_pp0_iter1_reg;
reg   [0:0] icmp_ln444_reg_1082_pp0_iter2_reg;
reg   [0:0] icmp_ln444_reg_1082_pp0_iter3_reg;
reg   [0:0] icmp_ln444_reg_1082_pp0_iter4_reg;
wire   [31:0] j_V_fu_545_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] and_ln118_3_fu_592_p2;
reg   [0:0] and_ln118_3_reg_1091_pp0_iter1_reg;
wire   [31:0] x_fu_613_p3;
reg   [31:0] x_reg_1095;
wire   [0:0] or_ln457_fu_621_p2;
reg   [0:0] or_ln457_reg_1101;
reg   [0:0] or_ln457_reg_1101_pp0_iter1_reg;
wire   [0:0] and_ln512_fu_626_p2;
reg   [0:0] and_ln512_reg_1108_pp0_iter1_reg;
reg   [0:0] and_ln512_reg_1108_pp0_iter2_reg;
reg   [0:0] and_ln512_reg_1108_pp0_iter3_reg;
wire   [1:0] trunc_ln493_3_fu_641_p1;
reg   [1:0] trunc_ln493_3_reg_1117;
reg   [9:0] k_buf_0_val_4_addr_reg_1124;
reg   [9:0] k_buf_0_val_5_addr_reg_1130;
wire   [7:0] src_kernel_win_0_va_6_fu_734_p3;
reg   [7:0] src_kernel_win_0_va_6_reg_1136;
reg   [7:0] src_kernel_win_0_va_6_reg_1136_pp0_iter3_reg;
reg   [7:0] src_kernel_win_0_va_6_reg_1136_pp0_iter4_reg;
wire   [7:0] src_kernel_win_0_va_7_fu_752_p3;
reg   [7:0] src_kernel_win_0_va_7_reg_1143;
reg   [7:0] src_kernel_win_0_va_7_reg_1143_pp0_iter3_reg;
wire   [7:0] src_kernel_win_0_va_8_fu_770_p3;
reg   [7:0] src_kernel_win_0_va_8_reg_1150;
wire   [7:0] select_ln162_fu_789_p3;
reg   [7:0] select_ln162_reg_1157;
wire   [7:0] select_ln162_3_fu_833_p3;
reg   [7:0] select_ln162_3_reg_1163;
wire   [7:0] select_ln162_6_fu_889_p3;
reg   [7:0] select_ln162_6_reg_1169;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
wire   [9:0] k_buf_0_val_3_address0;
reg    k_buf_0_val_3_ce0;
reg    k_buf_0_val_3_we0;
wire   [7:0] k_buf_0_val_3_q0;
wire   [9:0] k_buf_0_val_3_address1;
reg    k_buf_0_val_3_ce1;
reg    k_buf_0_val_3_we1;
wire   [9:0] k_buf_0_val_4_address0;
reg    k_buf_0_val_4_ce0;
reg    k_buf_0_val_4_we0;
wire   [7:0] k_buf_0_val_4_q0;
wire   [9:0] k_buf_0_val_4_address1;
reg    k_buf_0_val_4_ce1;
reg    k_buf_0_val_4_we1;
wire   [9:0] k_buf_0_val_5_address0;
reg    k_buf_0_val_5_ce0;
reg    k_buf_0_val_5_we0;
wire   [7:0] k_buf_0_val_5_q0;
wire   [9:0] k_buf_0_val_5_address1;
reg    k_buf_0_val_5_ce1;
reg    k_buf_0_val_5_we1;
reg   [31:0] t_V_reg_250;
wire    ap_CS_fsm_state9;
wire   [63:0] zext_ln835_fu_635_p1;
reg   [7:0] src_kernel_win_0_va_fu_122;
reg   [7:0] ap_sig_allocacmp_src_kernel_win_0_va_9;
reg   [7:0] src_kernel_win_0_va_1_fu_126;
reg   [7:0] ap_sig_allocacmp_src_kernel_win_0_va_10;
reg   [7:0] src_kernel_win_0_va_2_fu_130;
reg   [7:0] ap_sig_allocacmp_src_kernel_win_0_va_11;
reg   [7:0] src_kernel_win_0_va_3_fu_134;
reg   [7:0] ap_sig_allocacmp_src_kernel_win_0_va_12;
reg   [7:0] src_kernel_win_0_va_4_fu_138;
reg   [7:0] ap_sig_allocacmp_src_kernel_win_0_va_13;
reg   [7:0] src_kernel_win_0_va_5_fu_142;
reg   [7:0] ap_sig_allocacmp_src_kernel_win_0_va_14;
reg   [7:0] right_border_buf_0_s_fu_146;
wire   [7:0] col_buf_0_val_0_0_fu_665_p3;
reg   [7:0] right_border_buf_0_1_fu_150;
wire   [7:0] col_buf_0_val_2_0_fu_701_p3;
reg   [7:0] right_border_buf_0_2_fu_154;
wire   [7:0] col_buf_0_val_1_0_fu_683_p3;
reg    ap_block_pp0_stage0_01001;
wire   [30:0] tmp_fu_318_p4;
wire   [31:0] add_ln506_1_fu_351_p2;
wire   [0:0] tmp_128_fu_357_p3;
wire   [0:0] icmp_ln118_fu_371_p2;
wire   [0:0] xor_ln118_fu_365_p2;
wire   [0:0] tmp_129_fu_382_p3;
wire   [31:0] add_ln506_2_fu_397_p2;
wire   [0:0] tmp_130_fu_403_p3;
wire   [0:0] icmp_ln118_1_fu_417_p2;
wire   [0:0] xor_ln118_1_fu_411_p2;
wire   [0:0] tmp_131_fu_428_p3;
wire   [31:0] add_ln506_3_fu_443_p2;
wire   [0:0] tmp_132_fu_449_p3;
wire   [0:0] icmp_ln118_2_fu_463_p2;
wire   [0:0] xor_ln118_2_fu_457_p2;
wire   [0:0] tmp_133_fu_474_p3;
wire   [0:0] and_ln118_fu_376_p2;
wire   [31:0] select_ln121_fu_390_p3;
wire   [31:0] select_ln118_fu_489_p3;
wire   [31:0] sub_ln507_fu_497_p2;
wire   [0:0] and_ln118_1_fu_422_p2;
wire   [31:0] select_ln121_1_fu_436_p3;
wire   [31:0] select_ln118_1_fu_506_p3;
wire   [31:0] sub_ln507_1_fu_514_p2;
wire   [0:0] and_ln118_2_fu_468_p2;
wire   [31:0] select_ln121_2_fu_482_p3;
wire   [31:0] select_ln118_2_fu_523_p3;
wire   [31:0] sub_ln507_2_fu_531_p2;
wire   [30:0] tmp_134_fu_551_p4;
wire   [31:0] ImagLoc_x_fu_567_p2;
wire   [0:0] tmp_135_fu_573_p3;
wire   [0:0] icmp_ln118_3_fu_587_p2;
wire   [0:0] xor_ln118_3_fu_581_p2;
wire   [0:0] tmp_136_fu_598_p3;
wire   [31:0] select_ln121_3_fu_606_p3;
wire   [0:0] icmp_ln891_fu_561_p2;
wire   [31:0] sub_ln458_fu_631_p2;
wire   [7:0] tmp_8_fu_654_p5;
wire   [7:0] tmp_9_fu_672_p5;
wire   [7:0] tmp_10_fu_690_p5;
wire   [7:0] tmp_11_fu_723_p5;
wire   [7:0] tmp_12_fu_741_p5;
wire   [7:0] tmp_s_fu_759_p5;
wire   [0:0] icmp_ln162_fu_783_p2;
wire   [0:0] icmp_ln162_1_fu_803_p2;
wire   [7:0] select_ln162_1_fu_807_p3;
wire   [0:0] icmp_ln162_2_fu_813_p2;
wire   [7:0] select_ln162_2_fu_819_p3;
wire   [0:0] icmp_ln162_3_fu_827_p2;
wire   [0:0] icmp_ln162_4_fu_859_p2;
wire   [7:0] select_ln162_4_fu_863_p3;
wire   [0:0] icmp_ln162_5_fu_869_p2;
wire   [7:0] select_ln162_5_fu_875_p3;
wire   [0:0] icmp_ln162_6_fu_883_p2;
wire   [0:0] icmp_ln162_7_fu_909_p2;
reg   [3:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_predicate_op115_store_state4;
reg    ap_enable_operation_115;
reg    ap_enable_state4_pp0_iter1_stage0;
reg    ap_enable_operation_113;
reg    ap_enable_operation_131;
reg    ap_enable_state5_pp0_iter2_stage0;
reg    ap_predicate_op134_store_state5;
reg    ap_enable_operation_134;
reg    ap_predicate_op116_store_state4;
reg    ap_enable_operation_116;
wire    ap_enable_operation_111;
wire    ap_enable_operation_128;
reg    ap_predicate_op135_store_state5;
reg    ap_enable_operation_135;
reg    ap_predicate_op118_store_state4;
reg    ap_enable_operation_118;
wire    ap_enable_operation_108;
wire    ap_enable_operation_125;
reg    ap_predicate_op121_store_state4;
reg    ap_enable_operation_121;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
end

Erode_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
k_buf_0_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_3_address0),
    .ce0(k_buf_0_val_3_ce0),
    .we0(k_buf_0_val_3_we0),
    .d0(p_src_data_stream_V_dout),
    .q0(k_buf_0_val_3_q0),
    .address1(k_buf_0_val_3_address1),
    .ce1(k_buf_0_val_3_ce1),
    .we1(k_buf_0_val_3_we1),
    .d1(p_src_data_stream_V_dout)
);

Erode_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
k_buf_0_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_4_address0),
    .ce0(k_buf_0_val_4_ce0),
    .we0(k_buf_0_val_4_we0),
    .d0(p_src_data_stream_V_dout),
    .q0(k_buf_0_val_4_q0),
    .address1(k_buf_0_val_4_address1),
    .ce1(k_buf_0_val_4_ce1),
    .we1(k_buf_0_val_4_we1),
    .d1(k_buf_0_val_3_q0)
);

Erode_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
k_buf_0_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_5_address0),
    .ce0(k_buf_0_val_5_ce0),
    .we0(k_buf_0_val_5_we0),
    .d0(p_src_data_stream_V_dout),
    .q0(k_buf_0_val_5_q0),
    .address1(k_buf_0_val_5_address1),
    .ce1(k_buf_0_val_5_ce1),
    .we1(k_buf_0_val_5_we1),
    .d1(k_buf_0_val_4_q0)
);

skin_process_accejbC #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
skin_process_accejbC_U50(
    .din0(right_border_buf_0_s_fu_146),
    .din1(8'd0),
    .din2(8'd0),
    .din3(trunc_ln493_3_reg_1117),
    .dout(tmp_8_fu_654_p5)
);

skin_process_accejbC #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
skin_process_accejbC_U51(
    .din0(right_border_buf_0_2_fu_154),
    .din1(8'd0),
    .din2(8'd0),
    .din3(trunc_ln493_3_reg_1117),
    .dout(tmp_9_fu_672_p5)
);

skin_process_accejbC #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
skin_process_accejbC_U52(
    .din0(right_border_buf_0_1_fu_150),
    .din1(8'd0),
    .din2(8'd0),
    .din3(trunc_ln493_3_reg_1117),
    .dout(tmp_10_fu_690_p5)
);

skin_process_accejbC #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
skin_process_accejbC_U53(
    .din0(col_buf_0_val_0_0_fu_665_p3),
    .din1(col_buf_0_val_1_0_fu_683_p3),
    .din2(col_buf_0_val_2_0_fu_701_p3),
    .din3(trunc_ln493_reg_1067),
    .dout(tmp_11_fu_723_p5)
);

skin_process_accejbC #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
skin_process_accejbC_U54(
    .din0(col_buf_0_val_0_0_fu_665_p3),
    .din1(col_buf_0_val_1_0_fu_683_p3),
    .din2(col_buf_0_val_2_0_fu_701_p3),
    .din3(trunc_ln493_1_reg_1072),
    .dout(tmp_12_fu_741_p5)
);

skin_process_accejbC #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
skin_process_accejbC_U55(
    .din0(col_buf_0_val_0_0_fu_665_p3),
    .din1(col_buf_0_val_1_0_fu_683_p3),
    .din2(col_buf_0_val_2_0_fu_701_p3),
    .din3(trunc_ln493_2_reg_1077),
    .dout(tmp_s_fu_759_p5)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln443_fu_296_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((icmp_ln443_fu_296_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state3)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end else if (((icmp_ln443_fu_296_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln444_fu_540_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        t_V_6_reg_261 <= j_V_fu_545_p2;
    end else if (((icmp_ln443_fu_296_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        t_V_6_reg_261 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        t_V_reg_250 <= i_V_reg_1033;
    end else if ((~((ap_start == 1'b0) | (p_src_cols_V_empty_n == 1'b0) | (p_src_rows_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        t_V_reg_250 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (p_src_cols_V_empty_n == 1'b0) | (p_src_rows_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        add_ln443_1_reg_1008 <= add_ln443_1_fu_278_p2;
        add_ln443_reg_1003 <= add_ln443_fu_272_p2;
        add_ln458_reg_1013 <= add_ln458_fu_284_p2;
        add_ln506_reg_1019 <= add_ln506_fu_290_p2;
        cols_reg_998 <= p_src_cols_V_dout;
        stop_row_reg_989 <= p_src_rows_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln444_fu_540_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln118_3_reg_1091 <= and_ln118_3_fu_592_p2;
        and_ln512_reg_1108 <= and_ln512_fu_626_p2;
        or_ln457_reg_1101 <= or_ln457_fu_621_p2;
        x_reg_1095 <= x_fu_613_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln118_3_reg_1091_pp0_iter1_reg <= and_ln118_3_reg_1091;
        and_ln512_reg_1108_pp0_iter1_reg <= and_ln512_reg_1108;
        icmp_ln444_reg_1082 <= icmp_ln444_fu_540_p2;
        icmp_ln444_reg_1082_pp0_iter1_reg <= icmp_ln444_reg_1082;
        k_buf_0_val_4_addr_reg_1124 <= zext_ln835_fu_635_p1;
        k_buf_0_val_5_addr_reg_1130 <= zext_ln835_fu_635_p1;
        or_ln457_reg_1101_pp0_iter1_reg <= or_ln457_reg_1101;
        trunc_ln493_3_reg_1117 <= trunc_ln493_3_fu_641_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        and_ln512_reg_1108_pp0_iter2_reg <= and_ln512_reg_1108_pp0_iter1_reg;
        and_ln512_reg_1108_pp0_iter3_reg <= and_ln512_reg_1108_pp0_iter2_reg;
        and_ln512_reg_1108_pp0_iter4_reg <= and_ln512_reg_1108_pp0_iter3_reg;
        icmp_ln444_reg_1082_pp0_iter2_reg <= icmp_ln444_reg_1082_pp0_iter1_reg;
        icmp_ln444_reg_1082_pp0_iter3_reg <= icmp_ln444_reg_1082_pp0_iter2_reg;
        icmp_ln444_reg_1082_pp0_iter4_reg <= icmp_ln444_reg_1082_pp0_iter3_reg;
        src_kernel_win_0_va_6_reg_1136 <= src_kernel_win_0_va_6_fu_734_p3;
        src_kernel_win_0_va_6_reg_1136_pp0_iter3_reg <= src_kernel_win_0_va_6_reg_1136;
        src_kernel_win_0_va_6_reg_1136_pp0_iter4_reg <= src_kernel_win_0_va_6_reg_1136_pp0_iter3_reg;
        src_kernel_win_0_va_7_reg_1143 <= src_kernel_win_0_va_7_fu_752_p3;
        src_kernel_win_0_va_7_reg_1143_pp0_iter3_reg <= src_kernel_win_0_va_7_reg_1143;
        src_kernel_win_0_va_8_reg_1150 <= src_kernel_win_0_va_8_fu_770_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_V_reg_1033 <= i_V_fu_301_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln443_fu_296_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        icmp_ln879_1_reg_1056 <= icmp_ln879_1_fu_340_p2;
        icmp_ln879_reg_1052 <= icmp_ln879_fu_334_p2;
        icmp_ln887_reg_1038 <= icmp_ln887_fu_307_p2;
        icmp_ln899_1_reg_1060 <= icmp_ln899_1_fu_346_p2;
        icmp_ln899_reg_1047 <= icmp_ln899_fu_328_p2;
        trunc_ln493_1_reg_1072 <= trunc_ln493_1_fu_519_p1;
        trunc_ln493_2_reg_1077 <= trunc_ln493_2_fu_536_p1;
        trunc_ln493_reg_1067 <= trunc_ln493_fu_502_p1;
        xor_ln457_reg_1042 <= xor_ln457_fu_312_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln887_reg_1038 == 1'd1) & (icmp_ln899_reg_1047 == 1'd1) & (1'd1 == and_ln118_3_reg_1091_pp0_iter1_reg) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        right_border_buf_0_1_fu_150 <= col_buf_0_val_2_0_fu_701_p3;
        right_border_buf_0_2_fu_154 <= col_buf_0_val_1_0_fu_683_p3;
        right_border_buf_0_s_fu_146 <= col_buf_0_val_0_0_fu_665_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln512_reg_1108_pp0_iter2_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        select_ln162_3_reg_1163 <= select_ln162_3_fu_833_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln512_reg_1108_pp0_iter3_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        select_ln162_6_reg_1169 <= select_ln162_6_fu_889_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln512_reg_1108_pp0_iter1_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        select_ln162_reg_1157 <= select_ln162_fu_789_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln444_reg_1082_pp0_iter4_reg == 1'd0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_1_fu_126 <= src_kernel_win_0_va_fu_122;
        src_kernel_win_0_va_fu_122 <= src_kernel_win_0_va_6_reg_1136_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln444_reg_1082_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_2_fu_130 <= src_kernel_win_0_va_7_reg_1143_pp0_iter3_reg;
        src_kernel_win_0_va_3_fu_134 <= src_kernel_win_0_va_2_fu_130;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln444_reg_1082_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_4_fu_138 <= src_kernel_win_0_va_8_reg_1150;
        src_kernel_win_0_va_5_fu_142 <= src_kernel_win_0_va_4_fu_138;
    end
end

always @ (*) begin
    if ((icmp_ln444_fu_540_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln443_fu_296_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln443_fu_296_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln444_reg_1082_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_sig_allocacmp_src_kernel_win_0_va_10 = src_kernel_win_0_va_fu_122;
    end else begin
        ap_sig_allocacmp_src_kernel_win_0_va_10 = src_kernel_win_0_va_1_fu_126;
    end
end

always @ (*) begin
    if (((icmp_ln444_reg_1082_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_src_kernel_win_0_va_11 = src_kernel_win_0_va_7_reg_1143_pp0_iter3_reg;
    end else begin
        ap_sig_allocacmp_src_kernel_win_0_va_11 = src_kernel_win_0_va_2_fu_130;
    end
end

always @ (*) begin
    if (((icmp_ln444_reg_1082_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_src_kernel_win_0_va_12 = src_kernel_win_0_va_2_fu_130;
    end else begin
        ap_sig_allocacmp_src_kernel_win_0_va_12 = src_kernel_win_0_va_3_fu_134;
    end
end

always @ (*) begin
    if (((icmp_ln444_reg_1082_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_sig_allocacmp_src_kernel_win_0_va_13 = src_kernel_win_0_va_8_reg_1150;
    end else begin
        ap_sig_allocacmp_src_kernel_win_0_va_13 = src_kernel_win_0_va_4_fu_138;
    end
end

always @ (*) begin
    if (((icmp_ln444_reg_1082_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_sig_allocacmp_src_kernel_win_0_va_14 = src_kernel_win_0_va_4_fu_138;
    end else begin
        ap_sig_allocacmp_src_kernel_win_0_va_14 = src_kernel_win_0_va_5_fu_142;
    end
end

always @ (*) begin
    if (((icmp_ln444_reg_1082_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_sig_allocacmp_src_kernel_win_0_va_9 = src_kernel_win_0_va_6_reg_1136_pp0_iter4_reg;
    end else begin
        ap_sig_allocacmp_src_kernel_win_0_va_9 = src_kernel_win_0_va_fu_122;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_3_ce0 = 1'b1;
    end else begin
        k_buf_0_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_3_ce1 = 1'b1;
    end else begin
        k_buf_0_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln899_reg_1047 == 1'd0) & (icmp_ln879_1_reg_1056 == 1'd1) & (1'd1 == and_ln118_3_reg_1091) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_3_we0 = 1'b1;
    end else begin
        k_buf_0_val_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln887_reg_1038 == 1'd1) & (icmp_ln899_reg_1047 == 1'd1) & (1'd1 == and_ln118_3_reg_1091) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_3_we1 = 1'b1;
    end else begin
        k_buf_0_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_4_ce0 = 1'b1;
    end else begin
        k_buf_0_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_4_ce1 = 1'b1;
    end else begin
        k_buf_0_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln899_reg_1047 == 1'd0) & (icmp_ln879_reg_1052 == 1'd1) & (1'd1 == and_ln118_3_reg_1091) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_4_we0 = 1'b1;
    end else begin
        k_buf_0_val_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln887_reg_1038 == 1'd1) & (icmp_ln899_reg_1047 == 1'd1) & (1'd1 == and_ln118_3_reg_1091_pp0_iter1_reg) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_4_we1 = 1'b1;
    end else begin
        k_buf_0_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln899_reg_1047 == 1'd0) & (icmp_ln879_reg_1052 == 1'd1) & (1'd1 == and_ln118_3_reg_1091) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((or_ln457_reg_1101 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_5_ce0 = 1'b1;
    end else begin
        k_buf_0_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_5_ce1 = 1'b1;
    end else begin
        k_buf_0_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln899_reg_1047 == 1'd0) & (icmp_ln879_reg_1052 == 1'd1) & (1'd1 == and_ln118_3_reg_1091) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_5_we0 = 1'b1;
    end else begin
        k_buf_0_val_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln887_reg_1038 == 1'd1) & (icmp_ln899_reg_1047 == 1'd1) & (1'd1 == and_ln118_3_reg_1091_pp0_iter1_reg) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_5_we1 = 1'b1;
    end else begin
        k_buf_0_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln512_reg_1108_pp0_iter4_reg) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_dst_data_stream_V_blk_n = p_dst_data_stream_V_full_n;
    end else begin
        p_dst_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln512_reg_1108_pp0_iter4_reg) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_V_write = 1'b1;
    end else begin
        p_dst_data_stream_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_cols_V_blk_n = p_src_cols_V_empty_n;
    end else begin
        p_src_cols_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (p_src_cols_V_empty_n == 1'b0) | (p_src_rows_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_cols_V_read = 1'b1;
    end else begin
        p_src_cols_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln887_reg_1038 == 1'd1) & (icmp_ln899_reg_1047 == 1'd1) & (1'd1 == and_ln118_3_reg_1091) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln899_reg_1047 == 1'd0) & (1'd1 == and_ln118_3_reg_1091) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_src_data_stream_V_blk_n = p_src_data_stream_V_empty_n;
    end else begin
        p_src_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_predicate_op120_read_state4 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op114_read_state4 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        p_src_data_stream_V_read = 1'b1;
    end else begin
        p_src_data_stream_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_rows_V_blk_n = p_src_rows_V_empty_n;
    end else begin
        p_src_rows_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (p_src_cols_V_empty_n == 1'b0) | (p_src_rows_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_rows_V_read = 1'b1;
    end else begin
        p_src_rows_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (p_src_cols_V_empty_n == 1'b0) | (p_src_rows_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln443_fu_296_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln444_fu_540_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((icmp_ln444_fu_540_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ImagLoc_x_fu_567_p2 = ($signed(32'd4294967295) + $signed(t_V_6_reg_261));

assign add_ln443_1_fu_278_p2 = (p_src_rows_V_dout + 32'd2);

assign add_ln443_fu_272_p2 = (p_src_cols_V_dout + 32'd2);

assign add_ln458_fu_284_p2 = ($signed(p_src_cols_V_dout) + $signed(32'd4294967295));

assign add_ln506_1_fu_351_p2 = ($signed(32'd4294967295) + $signed(t_V_reg_250));

assign add_ln506_2_fu_397_p2 = ($signed(32'd4294967294) + $signed(t_V_reg_250));

assign add_ln506_3_fu_443_p2 = ($signed(32'd4294967293) + $signed(t_V_reg_250));

assign add_ln506_fu_290_p2 = ($signed(p_src_rows_V_dout) + $signed(32'd4294967295));

assign and_ln118_1_fu_422_p2 = (xor_ln118_1_fu_411_p2 & icmp_ln118_1_fu_417_p2);

assign and_ln118_2_fu_468_p2 = (xor_ln118_2_fu_457_p2 & icmp_ln118_2_fu_463_p2);

assign and_ln118_3_fu_592_p2 = (xor_ln118_3_fu_581_p2 & icmp_ln118_3_fu_587_p2);

assign and_ln118_fu_376_p2 = (xor_ln118_fu_365_p2 & icmp_ln118_fu_371_p2);

assign and_ln512_fu_626_p2 = (icmp_ln899_reg_1047 & icmp_ln891_fu_561_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((1'd1 == and_ln512_reg_1108_pp0_iter4_reg) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op120_read_state4 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op114_read_state4 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((1'd1 == and_ln512_reg_1108_pp0_iter4_reg) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op120_read_state4 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op114_read_state4 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((1'd1 == and_ln512_reg_1108_pp0_iter4_reg) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op120_read_state4 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op114_read_state4 == 1'b1)))));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (p_src_cols_V_empty_n == 1'b0) | (p_src_rows_V_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op120_read_state4 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op114_read_state4 == 1'b1)));
end

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_pp0_stage0_iter5 = ((1'd1 == and_ln512_reg_1108_pp0_iter4_reg) & (p_dst_data_stream_V_full_n == 1'b0));
end

assign ap_enable_operation_108 = (1'b1 == 1'b1);

assign ap_enable_operation_111 = (1'b1 == 1'b1);

always @ (*) begin
    ap_enable_operation_113 = (or_ln457_reg_1101 == 1'd1);
end

always @ (*) begin
    ap_enable_operation_115 = (ap_predicate_op115_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_116 = (ap_predicate_op116_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_118 = (ap_predicate_op118_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_121 = (ap_predicate_op121_store_state4 == 1'b1);
end

assign ap_enable_operation_125 = (1'b1 == 1'b1);

assign ap_enable_operation_128 = (1'b1 == 1'b1);

always @ (*) begin
    ap_enable_operation_131 = (or_ln457_reg_1101_pp0_iter1_reg == 1'd1);
end

always @ (*) begin
    ap_enable_operation_134 = (ap_predicate_op134_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_135 = (ap_predicate_op135_store_state5 == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_enable_state4_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state5_pp0_iter2_stage0 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_predicate_op114_read_state4 = ((icmp_ln899_reg_1047 == 1'd0) & (1'd1 == and_ln118_3_reg_1091));
end

always @ (*) begin
    ap_predicate_op115_store_state4 = ((icmp_ln899_reg_1047 == 1'd0) & (icmp_ln879_reg_1052 == 1'd1) & (1'd1 == and_ln118_3_reg_1091));
end

always @ (*) begin
    ap_predicate_op116_store_state4 = ((icmp_ln899_reg_1047 == 1'd0) & (icmp_ln879_reg_1052 == 1'd1) & (1'd1 == and_ln118_3_reg_1091));
end

always @ (*) begin
    ap_predicate_op118_store_state4 = ((icmp_ln899_reg_1047 == 1'd0) & (icmp_ln879_1_reg_1056 == 1'd1) & (1'd1 == and_ln118_3_reg_1091));
end

always @ (*) begin
    ap_predicate_op120_read_state4 = ((icmp_ln887_reg_1038 == 1'd1) & (icmp_ln899_reg_1047 == 1'd1) & (1'd1 == and_ln118_3_reg_1091));
end

always @ (*) begin
    ap_predicate_op121_store_state4 = ((icmp_ln887_reg_1038 == 1'd1) & (icmp_ln899_reg_1047 == 1'd1) & (1'd1 == and_ln118_3_reg_1091));
end

always @ (*) begin
    ap_predicate_op134_store_state5 = ((icmp_ln887_reg_1038 == 1'd1) & (icmp_ln899_reg_1047 == 1'd1) & (1'd1 == and_ln118_3_reg_1091_pp0_iter1_reg));
end

always @ (*) begin
    ap_predicate_op135_store_state5 = ((icmp_ln887_reg_1038 == 1'd1) & (icmp_ln899_reg_1047 == 1'd1) & (1'd1 == and_ln118_3_reg_1091_pp0_iter1_reg));
end

assign col_buf_0_val_0_0_fu_665_p3 = ((or_ln457_reg_1101_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_3_q0 : tmp_8_fu_654_p5);

assign col_buf_0_val_1_0_fu_683_p3 = ((or_ln457_reg_1101_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_4_q0 : tmp_9_fu_672_p5);

assign col_buf_0_val_2_0_fu_701_p3 = ((or_ln457_reg_1101_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_5_q0 : tmp_10_fu_690_p5);

assign i_V_fu_301_p2 = (t_V_reg_250 + 32'd1);

assign icmp_ln118_1_fu_417_p2 = (($signed(add_ln506_2_fu_397_p2) < $signed(stop_row_reg_989)) ? 1'b1 : 1'b0);

assign icmp_ln118_2_fu_463_p2 = (($signed(add_ln506_3_fu_443_p2) < $signed(stop_row_reg_989)) ? 1'b1 : 1'b0);

assign icmp_ln118_3_fu_587_p2 = (($signed(ImagLoc_x_fu_567_p2) < $signed(cols_reg_998)) ? 1'b1 : 1'b0);

assign icmp_ln118_fu_371_p2 = (($signed(add_ln506_1_fu_351_p2) < $signed(stop_row_reg_989)) ? 1'b1 : 1'b0);

assign icmp_ln162_1_fu_803_p2 = ((src_kernel_win_0_va_8_reg_1150 < select_ln162_reg_1157) ? 1'b1 : 1'b0);

assign icmp_ln162_2_fu_813_p2 = ((ap_sig_allocacmp_src_kernel_win_0_va_12 < select_ln162_1_fu_807_p3) ? 1'b1 : 1'b0);

assign icmp_ln162_3_fu_827_p2 = ((ap_sig_allocacmp_src_kernel_win_0_va_11 < select_ln162_2_fu_819_p3) ? 1'b1 : 1'b0);

assign icmp_ln162_4_fu_859_p2 = ((src_kernel_win_0_va_7_reg_1143_pp0_iter3_reg < select_ln162_3_reg_1163) ? 1'b1 : 1'b0);

assign icmp_ln162_5_fu_869_p2 = ((ap_sig_allocacmp_src_kernel_win_0_va_10 < select_ln162_4_fu_863_p3) ? 1'b1 : 1'b0);

assign icmp_ln162_6_fu_883_p2 = ((ap_sig_allocacmp_src_kernel_win_0_va_9 < select_ln162_5_fu_875_p3) ? 1'b1 : 1'b0);

assign icmp_ln162_7_fu_909_p2 = ((src_kernel_win_0_va_6_reg_1136_pp0_iter4_reg < select_ln162_6_reg_1169) ? 1'b1 : 1'b0);

assign icmp_ln162_fu_783_p2 = ((ap_sig_allocacmp_src_kernel_win_0_va_13 < ap_sig_allocacmp_src_kernel_win_0_va_14) ? 1'b1 : 1'b0);

assign icmp_ln443_fu_296_p2 = ((t_V_reg_250 == add_ln443_1_reg_1008) ? 1'b1 : 1'b0);

assign icmp_ln444_fu_540_p2 = ((t_V_6_reg_261 == add_ln443_reg_1003) ? 1'b1 : 1'b0);

assign icmp_ln879_1_fu_340_p2 = ((t_V_reg_250 == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln879_fu_334_p2 = ((t_V_reg_250 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln887_fu_307_p2 = ((t_V_reg_250 < stop_row_reg_989) ? 1'b1 : 1'b0);

assign icmp_ln891_fu_561_p2 = ((tmp_134_fu_551_p4 != 31'd0) ? 1'b1 : 1'b0);

assign icmp_ln899_1_fu_346_p2 = ((t_V_reg_250 > stop_row_reg_989) ? 1'b1 : 1'b0);

assign icmp_ln899_fu_328_p2 = ((tmp_fu_318_p4 != 31'd0) ? 1'b1 : 1'b0);

assign j_V_fu_545_p2 = (t_V_6_reg_261 + 32'd1);

assign k_buf_0_val_3_address0 = zext_ln835_fu_635_p1;

assign k_buf_0_val_3_address1 = zext_ln835_fu_635_p1;

assign k_buf_0_val_4_address0 = zext_ln835_fu_635_p1;

assign k_buf_0_val_4_address1 = k_buf_0_val_4_addr_reg_1124;

assign k_buf_0_val_5_address0 = zext_ln835_fu_635_p1;

assign k_buf_0_val_5_address1 = k_buf_0_val_5_addr_reg_1130;

assign or_ln457_fu_621_p2 = (xor_ln457_reg_1042 | icmp_ln118_3_fu_587_p2);

assign p_dst_data_stream_V_din = ((icmp_ln162_7_fu_909_p2[0:0] === 1'b1) ? src_kernel_win_0_va_6_reg_1136_pp0_iter4_reg : select_ln162_6_reg_1169);

assign select_ln118_1_fu_506_p3 = ((and_ln118_1_fu_422_p2[0:0] === 1'b1) ? add_ln506_2_fu_397_p2 : select_ln121_1_fu_436_p3);

assign select_ln118_2_fu_523_p3 = ((and_ln118_2_fu_468_p2[0:0] === 1'b1) ? add_ln506_3_fu_443_p2 : select_ln121_2_fu_482_p3);

assign select_ln118_fu_489_p3 = ((and_ln118_fu_376_p2[0:0] === 1'b1) ? add_ln506_1_fu_351_p2 : select_ln121_fu_390_p3);

assign select_ln121_1_fu_436_p3 = ((tmp_131_fu_428_p3[0:0] === 1'b1) ? 32'd0 : add_ln506_reg_1019);

assign select_ln121_2_fu_482_p3 = ((tmp_133_fu_474_p3[0:0] === 1'b1) ? 32'd0 : add_ln506_reg_1019);

assign select_ln121_3_fu_606_p3 = ((tmp_136_fu_598_p3[0:0] === 1'b1) ? 32'd0 : add_ln458_reg_1013);

assign select_ln121_fu_390_p3 = ((tmp_129_fu_382_p3[0:0] === 1'b1) ? 32'd0 : add_ln506_reg_1019);

assign select_ln162_1_fu_807_p3 = ((icmp_ln162_1_fu_803_p2[0:0] === 1'b1) ? src_kernel_win_0_va_8_reg_1150 : select_ln162_reg_1157);

assign select_ln162_2_fu_819_p3 = ((icmp_ln162_2_fu_813_p2[0:0] === 1'b1) ? ap_sig_allocacmp_src_kernel_win_0_va_12 : select_ln162_1_fu_807_p3);

assign select_ln162_3_fu_833_p3 = ((icmp_ln162_3_fu_827_p2[0:0] === 1'b1) ? ap_sig_allocacmp_src_kernel_win_0_va_11 : select_ln162_2_fu_819_p3);

assign select_ln162_4_fu_863_p3 = ((icmp_ln162_4_fu_859_p2[0:0] === 1'b1) ? src_kernel_win_0_va_7_reg_1143_pp0_iter3_reg : select_ln162_3_reg_1163);

assign select_ln162_5_fu_875_p3 = ((icmp_ln162_5_fu_869_p2[0:0] === 1'b1) ? ap_sig_allocacmp_src_kernel_win_0_va_10 : select_ln162_4_fu_863_p3);

assign select_ln162_6_fu_889_p3 = ((icmp_ln162_6_fu_883_p2[0:0] === 1'b1) ? ap_sig_allocacmp_src_kernel_win_0_va_9 : select_ln162_5_fu_875_p3);

assign select_ln162_fu_789_p3 = ((icmp_ln162_fu_783_p2[0:0] === 1'b1) ? ap_sig_allocacmp_src_kernel_win_0_va_13 : ap_sig_allocacmp_src_kernel_win_0_va_14);

assign src_kernel_win_0_va_6_fu_734_p3 = ((icmp_ln899_1_reg_1060[0:0] === 1'b1) ? tmp_11_fu_723_p5 : col_buf_0_val_0_0_fu_665_p3);

assign src_kernel_win_0_va_7_fu_752_p3 = ((icmp_ln899_1_reg_1060[0:0] === 1'b1) ? tmp_12_fu_741_p5 : col_buf_0_val_1_0_fu_683_p3);

assign src_kernel_win_0_va_8_fu_770_p3 = ((icmp_ln899_1_reg_1060[0:0] === 1'b1) ? tmp_s_fu_759_p5 : col_buf_0_val_2_0_fu_701_p3);

assign sub_ln458_fu_631_p2 = (add_ln458_reg_1013 - x_reg_1095);

assign sub_ln507_1_fu_514_p2 = (add_ln506_reg_1019 - select_ln118_1_fu_506_p3);

assign sub_ln507_2_fu_531_p2 = (add_ln506_reg_1019 - select_ln118_2_fu_523_p3);

assign sub_ln507_fu_497_p2 = (add_ln506_reg_1019 - select_ln118_fu_489_p3);

assign tmp_128_fu_357_p3 = add_ln506_1_fu_351_p2[32'd31];

assign tmp_129_fu_382_p3 = add_ln506_1_fu_351_p2[32'd31];

assign tmp_130_fu_403_p3 = add_ln506_2_fu_397_p2[32'd31];

assign tmp_131_fu_428_p3 = add_ln506_2_fu_397_p2[32'd31];

assign tmp_132_fu_449_p3 = add_ln506_3_fu_443_p2[32'd31];

assign tmp_133_fu_474_p3 = add_ln506_3_fu_443_p2[32'd31];

assign tmp_134_fu_551_p4 = {{t_V_6_reg_261[31:1]}};

assign tmp_135_fu_573_p3 = ImagLoc_x_fu_567_p2[32'd31];

assign tmp_136_fu_598_p3 = ImagLoc_x_fu_567_p2[32'd31];

assign tmp_fu_318_p4 = {{t_V_reg_250[31:1]}};

assign trunc_ln493_1_fu_519_p1 = sub_ln507_1_fu_514_p2[1:0];

assign trunc_ln493_2_fu_536_p1 = sub_ln507_2_fu_531_p2[1:0];

assign trunc_ln493_3_fu_641_p1 = sub_ln458_fu_631_p2[1:0];

assign trunc_ln493_fu_502_p1 = sub_ln507_fu_497_p2[1:0];

assign x_fu_613_p3 = ((and_ln118_3_fu_592_p2[0:0] === 1'b1) ? ImagLoc_x_fu_567_p2 : select_ln121_3_fu_606_p3);

assign xor_ln118_1_fu_411_p2 = (tmp_130_fu_403_p3 ^ 1'd1);

assign xor_ln118_2_fu_457_p2 = (tmp_132_fu_449_p3 ^ 1'd1);

assign xor_ln118_3_fu_581_p2 = (tmp_135_fu_573_p3 ^ 1'd1);

assign xor_ln118_fu_365_p2 = (tmp_128_fu_357_p3 ^ 1'd1);

assign xor_ln457_fu_312_p2 = (icmp_ln887_fu_307_p2 ^ 1'd1);

assign zext_ln835_fu_635_p1 = x_reg_1095;

endmodule //Erode
