// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module skin_and_gray (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        src_rows_V_dout,
        src_rows_V_empty_n,
        src_rows_V_read,
        src_cols_V_dout,
        src_cols_V_empty_n,
        src_cols_V_read,
        src_data_stream_0_V_dout,
        src_data_stream_0_V_empty_n,
        src_data_stream_0_V_read,
        src_data_stream_1_V_dout,
        src_data_stream_1_V_empty_n,
        src_data_stream_1_V_read,
        src_data_stream_2_V_dout,
        src_data_stream_2_V_empty_n,
        src_data_stream_2_V_read,
        dst_data_stream_V_din,
        dst_data_stream_V_full_n,
        dst_data_stream_V_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state9 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] src_rows_V_dout;
input   src_rows_V_empty_n;
output   src_rows_V_read;
input  [31:0] src_cols_V_dout;
input   src_cols_V_empty_n;
output   src_cols_V_read;
input  [7:0] src_data_stream_0_V_dout;
input   src_data_stream_0_V_empty_n;
output   src_data_stream_0_V_read;
input  [7:0] src_data_stream_1_V_dout;
input   src_data_stream_1_V_empty_n;
output   src_data_stream_1_V_read;
input  [7:0] src_data_stream_2_V_dout;
input   src_data_stream_2_V_empty_n;
output   src_data_stream_2_V_read;
output  [7:0] dst_data_stream_V_din;
input   dst_data_stream_V_full_n;
output   dst_data_stream_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg src_rows_V_read;
reg src_cols_V_read;
reg src_data_stream_0_V_read;
reg src_data_stream_1_V_read;
reg src_data_stream_2_V_read;
reg dst_data_stream_V_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    src_rows_V_blk_n;
reg    src_cols_V_blk_n;
reg    src_data_stream_0_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln7_reg_564;
reg    src_data_stream_1_V_blk_n;
reg    src_data_stream_2_V_blk_n;
reg    dst_data_stream_V_blk_n;
reg    ap_enable_reg_pp0_iter5;
reg   [0:0] icmp_ln7_reg_564_pp0_iter4_reg;
reg   [63:0] indvar_flatten_reg_207;
reg   [31:0] src_rows_V_read_reg_549;
reg    ap_block_state1;
reg   [31:0] src_cols_V_read_reg_554;
wire   [63:0] bound_fu_224_p2;
reg   [63:0] bound_reg_559;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln7_fu_230_p2;
wire    ap_block_state3_pp0_stage0_iter0;
reg    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state6_pp0_stage0_iter3;
wire    ap_block_state7_pp0_stage0_iter4;
reg    ap_block_state8_pp0_stage0_iter5;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln7_reg_564_pp0_iter1_reg;
reg   [0:0] icmp_ln7_reg_564_pp0_iter2_reg;
reg   [0:0] icmp_ln7_reg_564_pp0_iter3_reg;
wire   [63:0] add_ln7_fu_235_p2;
reg    ap_enable_reg_pp0_iter0;
reg   [7:0] tmp_7_reg_573;
reg   [7:0] tmp_9_reg_579;
wire   [17:0] zext_ln18_2_fu_241_p1;
reg   [17:0] zext_ln18_2_reg_585;
wire   [17:0] mul_ln19_1_fu_245_p2;
reg   [17:0] mul_ln19_1_reg_590;
wire   [17:0] mul_ln20_1_fu_251_p2;
reg   [17:0] mul_ln20_1_reg_595;
wire   [17:0] zext_ln18_1_fu_260_p1;
reg   [17:0] zext_ln18_1_reg_600;
wire   [17:0] mul_ln18_1_fu_477_p2;
reg   [17:0] mul_ln18_1_reg_605;
wire   [15:0] zext_ln18_4_fu_266_p1;
reg   [15:0] zext_ln18_4_reg_610;
wire  signed [17:0] grp_fu_489_p3;
reg  signed [17:0] add_ln19_1_reg_615;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] tmp_reg_621;
reg   [0:0] tmp_reg_621_pp0_iter3_reg;
wire  signed [17:0] grp_fu_498_p3;
reg  signed [17:0] add_ln20_1_reg_627;
reg   [0:0] tmp_3_reg_632;
reg   [0:0] tmp_3_reg_632_pp0_iter3_reg;
wire   [17:0] grp_fu_514_p3;
reg   [17:0] add_ln18_1_reg_638;
reg    ap_enable_reg_pp0_iter3;
wire   [35:0] trunc_ln19_fu_286_p1;
reg   [35:0] trunc_ln19_reg_643;
reg   [9:0] tmp_2_reg_648;
wire   [35:0] trunc_ln20_fu_301_p1;
reg   [35:0] trunc_ln20_reg_653;
reg   [9:0] tmp_5_reg_658;
wire   [0:0] icmp_ln23_3_fu_313_p2;
reg   [0:0] icmp_ln23_3_reg_663;
reg   [0:0] icmp_ln23_3_reg_663_pp0_iter4_reg;
wire   [37:0] mul_ln18_3_fu_543_p2;
reg   [37:0] mul_ln18_3_reg_668;
wire   [0:0] icmp_ln23_fu_427_p2;
reg   [0:0] icmp_ln23_reg_673;
wire   [0:0] icmp_ln23_1_fu_433_p2;
reg   [0:0] icmp_ln23_1_reg_678;
wire   [0:0] icmp_ln23_2_fu_439_p2;
reg   [0:0] icmp_ln23_2_reg_683;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_block_pp0_stage0_01001;
wire   [31:0] bound_fu_224_p0;
wire   [31:0] bound_fu_224_p1;
wire   [7:0] mul_ln19_1_fu_245_p1;
wire   [7:0] mul_ln20_1_fu_251_p1;
wire  signed [37:0] mul_ln19_3_fu_527_p2;
wire  signed [37:0] mul_ln20_3_fu_535_p2;
wire   [35:0] sub_ln19_fu_321_p2;
wire   [7:0] tmp_1_fu_326_p4;
wire  signed [18:0] sext_ln19_2_fu_336_p1;
wire  signed [18:0] sext_ln19_3_fu_340_p1;
wire   [18:0] select_ln19_fu_343_p3;
wire   [7:0] trunc_ln19_1_fu_350_p1;
wire   [7:0] sub_ln19_1_fu_354_p2;
wire   [7:0] trunc_ln19_2_fu_360_p1;
wire   [35:0] sub_ln20_fu_371_p2;
wire   [7:0] tmp_4_fu_376_p4;
wire  signed [18:0] sext_ln20_2_fu_386_p1;
wire  signed [18:0] sext_ln20_3_fu_390_p1;
wire   [18:0] select_ln20_fu_393_p3;
wire   [7:0] trunc_ln20_1_fu_400_p1;
wire   [7:0] sub_ln20_1_fu_404_p2;
wire   [7:0] trunc_ln20_2_fu_410_p1;
wire   [7:0] select_ln20_1_fu_414_p3;
wire   [7:0] cr_fu_421_p2;
wire   [7:0] select_ln19_1_fu_364_p3;
wire   [0:0] and_ln23_1_fu_449_p2;
wire   [0:0] and_ln23_fu_445_p2;
wire   [0:0] and_ln23_2_fu_453_p2;
wire   [7:0] trunc_ln_fu_459_p4;
wire   [10:0] mul_ln18_1_fu_477_p0;
wire   [7:0] mul_ln18_1_fu_477_p1;
wire  signed [8:0] grp_fu_482_p0;
wire   [7:0] grp_fu_482_p1;
wire   [9:0] grp_fu_489_p0;
wire   [7:0] grp_fu_489_p1;
wire  signed [17:0] grp_fu_482_p3;
wire   [9:0] grp_fu_498_p0;
wire   [7:0] grp_fu_498_p1;
wire  signed [17:0] grp_fu_506_p3;
wire  signed [7:0] grp_fu_506_p0;
wire   [7:0] grp_fu_506_p1;
wire   [9:0] grp_fu_514_p0;
wire   [7:0] grp_fu_514_p1;
wire   [17:0] grp_fu_520_p3;
wire   [7:0] grp_fu_520_p0;
wire   [7:0] grp_fu_520_p1;
wire   [19:0] mul_ln19_3_fu_527_p0;
wire   [19:0] mul_ln20_3_fu_535_p0;
wire   [19:0] mul_ln18_3_fu_543_p0;
wire   [17:0] mul_ln18_3_fu_543_p1;
wire    ap_CS_fsm_state9;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [63:0] bound_fu_224_p00;
wire   [63:0] bound_fu_224_p10;
wire   [16:0] grp_fu_482_p10;
wire   [17:0] grp_fu_489_p10;
wire   [17:0] grp_fu_498_p10;
wire   [15:0] grp_fu_506_p10;
wire   [37:0] mul_ln18_3_fu_543_p10;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
end

skin_process_accebkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 18 ))
skin_process_accebkb_U26(
    .din0(mul_ln18_1_fu_477_p0),
    .din1(mul_ln18_1_fu_477_p1),
    .dout(mul_ln18_1_fu_477_p2)
);

skin_process_accecud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
skin_process_accecud_U27(
    .din0(grp_fu_482_p0),
    .din1(grp_fu_482_p1),
    .din2(mul_ln19_1_reg_590),
    .dout(grp_fu_482_p3)
);

skin_process_accedEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
skin_process_accedEe_U28(
    .din0(grp_fu_489_p0),
    .din1(grp_fu_489_p1),
    .din2(grp_fu_482_p3),
    .dout(grp_fu_489_p3)
);

skin_process_accedEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
skin_process_accedEe_U29(
    .din0(grp_fu_498_p0),
    .din1(grp_fu_498_p1),
    .din2(grp_fu_506_p3),
    .dout(grp_fu_498_p3)
);

skin_process_acceeOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
skin_process_acceeOg_U30(
    .din0(grp_fu_506_p0),
    .din1(grp_fu_506_p1),
    .din2(mul_ln20_1_reg_595),
    .dout(grp_fu_506_p3)
);

skin_process_accefYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
skin_process_accefYi_U31(
    .din0(grp_fu_514_p0),
    .din1(grp_fu_514_p1),
    .din2(grp_fu_520_p3),
    .dout(grp_fu_514_p3)
);

skin_process_acceg8j #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
skin_process_acceg8j_U32(
    .din0(grp_fu_520_p0),
    .din1(grp_fu_520_p1),
    .din2(mul_ln18_1_reg_605),
    .dout(grp_fu_520_p3)
);

skin_process_accehbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 38 ))
skin_process_accehbi_U33(
    .din0(mul_ln19_3_fu_527_p0),
    .din1(add_ln19_1_reg_615),
    .dout(mul_ln19_3_fu_527_p2)
);

skin_process_accehbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 38 ))
skin_process_accehbi_U34(
    .din0(mul_ln20_3_fu_535_p0),
    .din1(add_ln20_1_reg_627),
    .dout(mul_ln20_3_fu_535_p2)
);

skin_process_acceibs #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 38 ))
skin_process_acceibs_U35(
    .din0(mul_ln18_3_fu_543_p0),
    .din1(mul_ln18_3_fu_543_p1),
    .dout(mul_ln18_3_fu_543_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state9)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state2)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state3)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end else if ((1'b1 == ap_CS_fsm_state2)) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln7_fu_230_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indvar_flatten_reg_207 <= add_ln7_fu_235_p2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        indvar_flatten_reg_207 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln7_reg_564_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln18_1_reg_638 <= grp_fu_514_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln7_reg_564_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln19_1_reg_615 <= grp_fu_489_p3;
        add_ln20_1_reg_627 <= grp_fu_498_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bound_reg_559 <= bound_fu_224_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln7_reg_564_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln23_1_reg_678 <= icmp_ln23_1_fu_433_p2;
        icmp_ln23_2_reg_683 <= icmp_ln23_2_fu_439_p2;
        icmp_ln23_reg_673 <= icmp_ln23_fu_427_p2;
        mul_ln18_3_reg_668 <= mul_ln18_3_fu_543_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln7_reg_564_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln23_3_reg_663 <= icmp_ln23_3_fu_313_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln23_3_reg_663_pp0_iter4_reg <= icmp_ln23_3_reg_663;
        icmp_ln7_reg_564_pp0_iter2_reg <= icmp_ln7_reg_564_pp0_iter1_reg;
        icmp_ln7_reg_564_pp0_iter3_reg <= icmp_ln7_reg_564_pp0_iter2_reg;
        icmp_ln7_reg_564_pp0_iter4_reg <= icmp_ln7_reg_564_pp0_iter3_reg;
        tmp_3_reg_632_pp0_iter3_reg <= tmp_3_reg_632;
        tmp_reg_621_pp0_iter3_reg <= tmp_reg_621;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln7_reg_564 <= icmp_ln7_fu_230_p2;
        icmp_ln7_reg_564_pp0_iter1_reg <= icmp_ln7_reg_564;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln7_reg_564_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        mul_ln18_1_reg_605 <= mul_ln18_1_fu_477_p2;
        tmp_3_reg_632 <= grp_fu_498_p3[32'd17];
        tmp_reg_621 <= grp_fu_489_p3[32'd17];
        zext_ln18_1_reg_600[7 : 0] <= zext_ln18_1_fu_260_p1[7 : 0];
        zext_ln18_4_reg_610[7 : 0] <= zext_ln18_4_fu_266_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln7_reg_564 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        mul_ln19_1_reg_590 <= mul_ln19_1_fu_245_p2;
        mul_ln20_1_reg_595 <= mul_ln20_1_fu_251_p2;
        tmp_7_reg_573 <= src_data_stream_0_V_dout;
        tmp_9_reg_579 <= src_data_stream_2_V_dout;
        zext_ln18_2_reg_585[7 : 0] <= zext_ln18_2_fu_241_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (src_cols_V_empty_n == 1'b0) | (src_rows_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        src_cols_V_read_reg_554 <= src_cols_V_dout;
        src_rows_V_read_reg_549 <= src_rows_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_reg_621 == 1'd0) & (icmp_ln7_reg_564_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_2_reg_648 <= {{mul_ln19_3_fu_527_p2[37:28]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_reg_632 == 1'd0) & (icmp_ln7_reg_564_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_5_reg_658 <= {{mul_ln20_3_fu_535_p2[37:28]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln7_reg_564_pp0_iter2_reg == 1'd0) & (tmp_reg_621 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        trunc_ln19_reg_643 <= trunc_ln19_fu_286_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln7_reg_564_pp0_iter2_reg == 1'd0) & (tmp_3_reg_632 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        trunc_ln20_reg_653 <= trunc_ln20_fu_301_p1;
    end
end

always @ (*) begin
    if ((icmp_ln7_fu_230_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln7_reg_564_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        dst_data_stream_V_blk_n = dst_data_stream_V_full_n;
    end else begin
        dst_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln7_reg_564_pp0_iter4_reg == 1'd0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        dst_data_stream_V_write = 1'b1;
    end else begin
        dst_data_stream_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        src_cols_V_blk_n = src_cols_V_empty_n;
    end else begin
        src_cols_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (src_cols_V_empty_n == 1'b0) | (src_rows_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        src_cols_V_read = 1'b1;
    end else begin
        src_cols_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln7_reg_564 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        src_data_stream_0_V_blk_n = src_data_stream_0_V_empty_n;
    end else begin
        src_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln7_reg_564 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_data_stream_0_V_read = 1'b1;
    end else begin
        src_data_stream_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln7_reg_564 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        src_data_stream_1_V_blk_n = src_data_stream_1_V_empty_n;
    end else begin
        src_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln7_reg_564 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_data_stream_1_V_read = 1'b1;
    end else begin
        src_data_stream_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln7_reg_564 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        src_data_stream_2_V_blk_n = src_data_stream_2_V_empty_n;
    end else begin
        src_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln7_reg_564 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_data_stream_2_V_read = 1'b1;
    end else begin
        src_data_stream_2_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        src_rows_V_blk_n = src_rows_V_empty_n;
    end else begin
        src_rows_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (src_cols_V_empty_n == 1'b0) | (src_rows_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        src_rows_V_read = 1'b1;
    end else begin
        src_rows_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (src_cols_V_empty_n == 1'b0) | (src_rows_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln7_fu_230_p2 == 1'd1)) & ~((ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln7_fu_230_p2 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln7_fu_235_p2 = (indvar_flatten_reg_207 + 64'd1);

assign and_ln23_1_fu_449_p2 = (icmp_ln23_3_reg_663_pp0_iter4_reg & icmp_ln23_2_reg_683);

assign and_ln23_2_fu_453_p2 = (and_ln23_fu_445_p2 & and_ln23_1_fu_449_p2);

assign and_ln23_fu_445_p2 = (icmp_ln23_reg_673 & icmp_ln23_1_reg_678);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((icmp_ln7_reg_564_pp0_iter4_reg == 1'd0) & (dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln7_reg_564 == 1'd0) & (src_data_stream_2_V_empty_n == 1'b0)) | ((icmp_ln7_reg_564 == 1'd0) & (src_data_stream_1_V_empty_n == 1'b0)) | ((icmp_ln7_reg_564 == 1'd0) & (src_data_stream_0_V_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((icmp_ln7_reg_564_pp0_iter4_reg == 1'd0) & (dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln7_reg_564 == 1'd0) & (src_data_stream_2_V_empty_n == 1'b0)) | ((icmp_ln7_reg_564 == 1'd0) & (src_data_stream_1_V_empty_n == 1'b0)) | ((icmp_ln7_reg_564 == 1'd0) & (src_data_stream_0_V_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((icmp_ln7_reg_564_pp0_iter4_reg == 1'd0) & (dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln7_reg_564 == 1'd0) & (src_data_stream_2_V_empty_n == 1'b0)) | ((icmp_ln7_reg_564 == 1'd0) & (src_data_stream_1_V_empty_n == 1'b0)) | ((icmp_ln7_reg_564 == 1'd0) & (src_data_stream_0_V_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (src_cols_V_empty_n == 1'b0) | (src_rows_V_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = (((icmp_ln7_reg_564 == 1'd0) & (src_data_stream_2_V_empty_n == 1'b0)) | ((icmp_ln7_reg_564 == 1'd0) & (src_data_stream_1_V_empty_n == 1'b0)) | ((icmp_ln7_reg_564 == 1'd0) & (src_data_stream_0_V_empty_n == 1'b0)));
end

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_pp0_stage0_iter5 = ((icmp_ln7_reg_564_pp0_iter4_reg == 1'd0) & (dst_data_stream_V_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign bound_fu_224_p0 = bound_fu_224_p00;

assign bound_fu_224_p00 = src_cols_V_read_reg_554;

assign bound_fu_224_p1 = bound_fu_224_p10;

assign bound_fu_224_p10 = src_rows_V_read_reg_549;

assign bound_fu_224_p2 = (bound_fu_224_p0 * bound_fu_224_p1);

assign cr_fu_421_p2 = (select_ln20_1_fu_414_p3 ^ 8'd128);

assign dst_data_stream_V_din = ((and_ln23_2_fu_453_p2[0:0] === 1'b1) ? trunc_ln_fu_459_p4 : 8'd0);

assign grp_fu_482_p0 = 17'd130903;

assign grp_fu_482_p1 = grp_fu_482_p10;

assign grp_fu_482_p10 = tmp_9_reg_579;

assign grp_fu_489_p0 = 18'd500;

assign grp_fu_489_p1 = grp_fu_489_p10;

assign grp_fu_489_p10 = tmp_7_reg_573;

assign grp_fu_498_p0 = 18'd500;

assign grp_fu_498_p1 = grp_fu_498_p10;

assign grp_fu_498_p10 = tmp_9_reg_579;

assign grp_fu_506_p0 = 16'd65455;

assign grp_fu_506_p1 = grp_fu_506_p10;

assign grp_fu_506_p10 = tmp_7_reg_573;

assign grp_fu_514_p0 = 18'd299;

assign grp_fu_514_p1 = zext_ln18_1_reg_600;

assign grp_fu_520_p0 = 16'd114;

assign grp_fu_520_p1 = zext_ln18_4_reg_610;

assign icmp_ln23_1_fu_433_p2 = ((cr_fu_421_p2 < 8'd174) ? 1'b1 : 1'b0);

assign icmp_ln23_2_fu_439_p2 = (($signed(select_ln19_1_fu_364_p3) > $signed(8'd204)) ? 1'b1 : 1'b0);

assign icmp_ln23_3_fu_313_p2 = (($signed(add_ln19_1_reg_615) < $signed(18'd261145)) ? 1'b1 : 1'b0);

assign icmp_ln23_fu_427_p2 = ((cr_fu_421_p2 > 8'd132) ? 1'b1 : 1'b0);

assign icmp_ln7_fu_230_p2 = ((indvar_flatten_reg_207 == bound_reg_559) ? 1'b1 : 1'b0);

assign mul_ln18_1_fu_477_p0 = 18'd587;

assign mul_ln18_1_fu_477_p1 = zext_ln18_2_reg_585;

assign mul_ln18_3_fu_543_p0 = 38'd268436;

assign mul_ln18_3_fu_543_p1 = mul_ln18_3_fu_543_p10;

assign mul_ln18_3_fu_543_p10 = add_ln18_1_reg_638;

assign mul_ln19_1_fu_245_p1 = zext_ln18_2_fu_241_p1;

assign mul_ln19_1_fu_245_p2 = ($signed(18'd261813) * $signed({{1'b0}, {mul_ln19_1_fu_245_p1}}));

assign mul_ln19_3_fu_527_p0 = 38'd268436;

assign mul_ln20_1_fu_251_p1 = zext_ln18_2_fu_241_p1;

assign mul_ln20_1_fu_251_p2 = ($signed(18'd261725) * $signed({{1'b0}, {mul_ln20_1_fu_251_p1}}));

assign mul_ln20_3_fu_535_p0 = 38'd268436;

assign select_ln19_1_fu_364_p3 = ((tmp_reg_621_pp0_iter3_reg[0:0] === 1'b1) ? sub_ln19_1_fu_354_p2 : trunc_ln19_2_fu_360_p1);

assign select_ln19_fu_343_p3 = ((tmp_reg_621_pp0_iter3_reg[0:0] === 1'b1) ? sext_ln19_2_fu_336_p1 : sext_ln19_3_fu_340_p1);

assign select_ln20_1_fu_414_p3 = ((tmp_3_reg_632_pp0_iter3_reg[0:0] === 1'b1) ? sub_ln20_1_fu_404_p2 : trunc_ln20_2_fu_410_p1);

assign select_ln20_fu_393_p3 = ((tmp_3_reg_632_pp0_iter3_reg[0:0] === 1'b1) ? sext_ln20_2_fu_386_p1 : sext_ln20_3_fu_390_p1);

assign sext_ln19_2_fu_336_p1 = $signed(tmp_1_fu_326_p4);

assign sext_ln19_3_fu_340_p1 = $signed(tmp_2_reg_648);

assign sext_ln20_2_fu_386_p1 = $signed(tmp_4_fu_376_p4);

assign sext_ln20_3_fu_390_p1 = $signed(tmp_5_reg_658);

assign sub_ln19_1_fu_354_p2 = (8'd0 - trunc_ln19_1_fu_350_p1);

assign sub_ln19_fu_321_p2 = (36'd0 - trunc_ln19_reg_643);

assign sub_ln20_1_fu_404_p2 = (8'd0 - trunc_ln20_1_fu_400_p1);

assign sub_ln20_fu_371_p2 = (36'd0 - trunc_ln20_reg_653);

assign tmp_1_fu_326_p4 = {{sub_ln19_fu_321_p2[35:28]}};

assign tmp_4_fu_376_p4 = {{sub_ln20_fu_371_p2[35:28]}};

assign trunc_ln19_1_fu_350_p1 = select_ln19_fu_343_p3[7:0];

assign trunc_ln19_2_fu_360_p1 = select_ln19_fu_343_p3[7:0];

assign trunc_ln19_fu_286_p1 = mul_ln19_3_fu_527_p2[35:0];

assign trunc_ln20_1_fu_400_p1 = select_ln20_fu_393_p3[7:0];

assign trunc_ln20_2_fu_410_p1 = select_ln20_fu_393_p3[7:0];

assign trunc_ln20_fu_301_p1 = mul_ln20_3_fu_535_p2[35:0];

assign trunc_ln_fu_459_p4 = {{mul_ln18_3_reg_668[35:28]}};

assign zext_ln18_1_fu_260_p1 = tmp_9_reg_579;

assign zext_ln18_2_fu_241_p1 = src_data_stream_1_V_dout;

assign zext_ln18_4_fu_266_p1 = tmp_7_reg_573;

always @ (posedge ap_clk) begin
    zext_ln18_2_reg_585[17:8] <= 10'b0000000000;
    zext_ln18_1_reg_600[17:8] <= 10'b0000000000;
    zext_ln18_4_reg_610[15:8] <= 8'b00000000;
end

endmodule //skin_and_gray
