// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="skin_process_accel,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=11.000000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=12,HLS_SYN_DSP=47,HLS_SYN_FF=30604,HLS_SYN_LUT=41304,HLS_VERSION=2019_2}" *)

module skin_process_accel (
        s_axi_ctrl_AWVALID,
        s_axi_ctrl_AWREADY,
        s_axi_ctrl_AWADDR,
        s_axi_ctrl_WVALID,
        s_axi_ctrl_WREADY,
        s_axi_ctrl_WDATA,
        s_axi_ctrl_WSTRB,
        s_axi_ctrl_ARVALID,
        s_axi_ctrl_ARREADY,
        s_axi_ctrl_ARADDR,
        s_axi_ctrl_RVALID,
        s_axi_ctrl_RREADY,
        s_axi_ctrl_RDATA,
        s_axi_ctrl_RRESP,
        s_axi_ctrl_BVALID,
        s_axi_ctrl_BREADY,
        s_axi_ctrl_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        input_stream_TDATA,
        input_stream_TKEEP,
        input_stream_TSTRB,
        input_stream_TUSER,
        input_stream_TLAST,
        input_stream_TID,
        input_stream_TDEST,
        input_stream_TVALID,
        input_stream_TREADY
);

parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 13;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_ADDR_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_ctrl_AWVALID;
output   s_axi_ctrl_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_ctrl_AWADDR;
input   s_axi_ctrl_WVALID;
output   s_axi_ctrl_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_ctrl_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_ctrl_WSTRB;
input   s_axi_ctrl_ARVALID;
output   s_axi_ctrl_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_ctrl_ARADDR;
output   s_axi_ctrl_RVALID;
input   s_axi_ctrl_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_ctrl_RDATA;
output  [1:0] s_axi_ctrl_RRESP;
output   s_axi_ctrl_BVALID;
input   s_axi_ctrl_BREADY;
output  [1:0] s_axi_ctrl_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
input  [23:0] input_stream_TDATA;
input  [2:0] input_stream_TKEEP;
input  [2:0] input_stream_TSTRB;
input  [0:0] input_stream_TUSER;
input  [0:0] input_stream_TLAST;
input  [0:0] input_stream_TID;
input  [0:0] input_stream_TDEST;
input   input_stream_TVALID;
output   input_stream_TREADY;

 reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire   [31:0] hog_features_q0;
wire   [31:0] rows;
wire   [31:0] cols;
wire    Block_Mat_exit11_pro_U0_ap_start;
wire    Block_Mat_exit11_pro_U0_start_full_n;
wire    Block_Mat_exit11_pro_U0_ap_done;
wire    Block_Mat_exit11_pro_U0_ap_continue;
wire    Block_Mat_exit11_pro_U0_ap_idle;
wire    Block_Mat_exit11_pro_U0_ap_ready;
wire    Block_Mat_exit11_pro_U0_start_out;
wire    Block_Mat_exit11_pro_U0_start_write;
wire   [31:0] Block_Mat_exit11_pro_U0_img_rgb_rows_V_out_din;
wire    Block_Mat_exit11_pro_U0_img_rgb_rows_V_out_write;
wire   [31:0] Block_Mat_exit11_pro_U0_img_rgb_cols_V_out_din;
wire    Block_Mat_exit11_pro_U0_img_rgb_cols_V_out_write;
wire   [31:0] Block_Mat_exit11_pro_U0_img_mask_gray_rows_V_out_din;
wire    Block_Mat_exit11_pro_U0_img_mask_gray_rows_V_out_write;
wire   [31:0] Block_Mat_exit11_pro_U0_img_mask_gray_cols_V_out_din;
wire    Block_Mat_exit11_pro_U0_img_mask_gray_cols_V_out_write;
wire   [31:0] Block_Mat_exit11_pro_U0_img_erode_rows_V_out_din;
wire    Block_Mat_exit11_pro_U0_img_erode_rows_V_out_write;
wire   [31:0] Block_Mat_exit11_pro_U0_img_erode_cols_V_out_din;
wire    Block_Mat_exit11_pro_U0_img_erode_cols_V_out_write;
wire   [31:0] Block_Mat_exit11_pro_U0_img_dilate_rows_V_out_din;
wire    Block_Mat_exit11_pro_U0_img_dilate_rows_V_out_write;
wire   [31:0] Block_Mat_exit11_pro_U0_img_dilate_cols_V_out_din;
wire    Block_Mat_exit11_pro_U0_img_dilate_cols_V_out_write;
wire    AXIvideo2Mat_U0_ap_start;
wire    AXIvideo2Mat_U0_ap_done;
wire    AXIvideo2Mat_U0_ap_continue;
wire    AXIvideo2Mat_U0_ap_idle;
wire    AXIvideo2Mat_U0_ap_ready;
wire    AXIvideo2Mat_U0_start_out;
wire    AXIvideo2Mat_U0_start_write;
wire    AXIvideo2Mat_U0_input_stream_TREADY;
wire    AXIvideo2Mat_U0_img_rows_V_read;
wire    AXIvideo2Mat_U0_img_cols_V_read;
wire   [7:0] AXIvideo2Mat_U0_img_data_stream_0_V_din;
wire    AXIvideo2Mat_U0_img_data_stream_0_V_write;
wire   [7:0] AXIvideo2Mat_U0_img_data_stream_1_V_din;
wire    AXIvideo2Mat_U0_img_data_stream_1_V_write;
wire   [7:0] AXIvideo2Mat_U0_img_data_stream_2_V_din;
wire    AXIvideo2Mat_U0_img_data_stream_2_V_write;
wire   [31:0] AXIvideo2Mat_U0_img_rows_V_out_din;
wire    AXIvideo2Mat_U0_img_rows_V_out_write;
wire   [31:0] AXIvideo2Mat_U0_img_cols_V_out_din;
wire    AXIvideo2Mat_U0_img_cols_V_out_write;
wire    skin_and_gray_U0_ap_start;
wire    skin_and_gray_U0_ap_done;
wire    skin_and_gray_U0_ap_continue;
wire    skin_and_gray_U0_ap_idle;
wire    skin_and_gray_U0_ap_ready;
wire    skin_and_gray_U0_src_rows_V_read;
wire    skin_and_gray_U0_src_cols_V_read;
wire    skin_and_gray_U0_src_data_stream_0_V_read;
wire    skin_and_gray_U0_src_data_stream_1_V_read;
wire    skin_and_gray_U0_src_data_stream_2_V_read;
wire   [7:0] skin_and_gray_U0_dst_data_stream_V_din;
wire    skin_and_gray_U0_dst_data_stream_V_write;
wire    Erode_U0_ap_start;
wire    Erode_U0_ap_done;
wire    Erode_U0_ap_continue;
wire    Erode_U0_ap_idle;
wire    Erode_U0_ap_ready;
wire    Erode_U0_p_src_rows_V_read;
wire    Erode_U0_p_src_cols_V_read;
wire    Erode_U0_p_src_data_stream_V_read;
wire   [7:0] Erode_U0_p_dst_data_stream_V_din;
wire    Erode_U0_p_dst_data_stream_V_write;
wire    Dilate_U0_ap_start;
wire    Dilate_U0_ap_done;
wire    Dilate_U0_ap_continue;
wire    Dilate_U0_ap_idle;
wire    Dilate_U0_ap_ready;
wire    Dilate_U0_p_src_rows_V_read;
wire    Dilate_U0_p_src_cols_V_read;
wire    Dilate_U0_p_src_data_stream_V_read;
wire   [7:0] Dilate_U0_p_dst_data_stream_V_din;
wire    Dilate_U0_p_dst_data_stream_V_write;
wire    Resize_U0_ap_start;
wire    Resize_U0_ap_done;
wire    Resize_U0_ap_continue;
wire    Resize_U0_ap_idle;
wire    Resize_U0_ap_ready;
wire    Resize_U0_p_src_rows_V_read;
wire    Resize_U0_p_src_cols_V_read;
wire    Resize_U0_p_src_data_stream_V_read;
wire   [7:0] Resize_U0_p_dst_data_stream_V_din;
wire    Resize_U0_p_dst_data_stream_V_write;
wire    compute_real_hog_U0_ap_start;
wire    compute_real_hog_U0_ap_done;
wire    compute_real_hog_U0_ap_continue;
wire    compute_real_hog_U0_ap_idle;
wire    compute_real_hog_U0_ap_ready;
wire    compute_real_hog_U0_src_data_stream_V_read;
wire   [8:0] compute_real_hog_U0_features_address0;
wire    compute_real_hog_U0_features_ce0;
wire    compute_real_hog_U0_features_we0;
wire   [31:0] compute_real_hog_U0_features_d0;
wire    ap_sync_continue;
wire    img_rgb_rows_V_c_full_n;
wire   [31:0] img_rgb_rows_V_c_dout;
wire    img_rgb_rows_V_c_empty_n;
wire    img_rgb_cols_V_c_full_n;
wire   [31:0] img_rgb_cols_V_c_dout;
wire    img_rgb_cols_V_c_empty_n;
wire    img_mask_gray_rows_V_full_n;
wire   [31:0] img_mask_gray_rows_V_dout;
wire    img_mask_gray_rows_V_empty_n;
wire    img_mask_gray_cols_V_full_n;
wire   [31:0] img_mask_gray_cols_V_dout;
wire    img_mask_gray_cols_V_empty_n;
wire    img_erode_rows_V_c_full_n;
wire   [31:0] img_erode_rows_V_c_dout;
wire    img_erode_rows_V_c_empty_n;
wire    img_erode_cols_V_c_full_n;
wire   [31:0] img_erode_cols_V_c_dout;
wire    img_erode_cols_V_c_empty_n;
wire    img_dilate_rows_V_c_full_n;
wire   [31:0] img_dilate_rows_V_c_dout;
wire    img_dilate_rows_V_c_empty_n;
wire    img_dilate_cols_V_c_full_n;
wire   [31:0] img_dilate_cols_V_c_dout;
wire    img_dilate_cols_V_c_empty_n;
wire    img_rgb_data_stream_s_full_n;
wire   [7:0] img_rgb_data_stream_s_dout;
wire    img_rgb_data_stream_s_empty_n;
wire    img_rgb_data_stream_1_full_n;
wire   [7:0] img_rgb_data_stream_1_dout;
wire    img_rgb_data_stream_1_empty_n;
wire    img_rgb_data_stream_2_full_n;
wire   [7:0] img_rgb_data_stream_2_dout;
wire    img_rgb_data_stream_2_empty_n;
wire    img_rgb_rows_V_c25_full_n;
wire   [31:0] img_rgb_rows_V_c25_dout;
wire    img_rgb_rows_V_c25_empty_n;
wire    img_rgb_cols_V_c26_full_n;
wire   [31:0] img_rgb_cols_V_c26_dout;
wire    img_rgb_cols_V_c26_empty_n;
wire    img_mask_gray_data_s_full_n;
wire   [7:0] img_mask_gray_data_s_dout;
wire    img_mask_gray_data_s_empty_n;
wire    img_erode_data_strea_full_n;
wire   [7:0] img_erode_data_strea_dout;
wire    img_erode_data_strea_empty_n;
wire    img_dilate_data_stre_full_n;
wire   [7:0] img_dilate_data_stre_dout;
wire    img_dilate_data_stre_empty_n;
wire    img_resized_data_str_full_n;
wire   [7:0] img_resized_data_str_dout;
wire    img_resized_data_str_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_Block_Mat_exit11_pro_U0_ap_ready;
wire    ap_sync_Block_Mat_exit11_pro_U0_ap_ready;
reg   [1:0] Block_Mat_exit11_pro_U0_ap_ready_count;
reg    ap_sync_reg_AXIvideo2Mat_U0_ap_ready;
wire    ap_sync_AXIvideo2Mat_U0_ap_ready;
reg   [1:0] AXIvideo2Mat_U0_ap_ready_count;
reg    ap_sync_reg_compute_real_hog_U0_ap_ready;
wire    ap_sync_compute_real_hog_U0_ap_ready;
reg   [1:0] compute_real_hog_U0_ap_ready_count;
wire   [0:0] start_for_Erode_U0_din;
wire    start_for_Erode_U0_full_n;
wire   [0:0] start_for_Erode_U0_dout;
wire    start_for_Erode_U0_empty_n;
wire   [0:0] start_for_Dilate_U0_din;
wire    start_for_Dilate_U0_full_n;
wire   [0:0] start_for_Dilate_U0_dout;
wire    start_for_Dilate_U0_empty_n;
wire   [0:0] start_for_Resize_U0_din;
wire    start_for_Resize_U0_full_n;
wire   [0:0] start_for_Resize_U0_dout;
wire    start_for_Resize_U0_empty_n;
wire   [0:0] start_for_skin_and_gray_U0_din;
wire    start_for_skin_and_gray_U0_full_n;
wire   [0:0] start_for_skin_and_gray_U0_dout;
wire    start_for_skin_and_gray_U0_empty_n;
wire    skin_and_gray_U0_start_full_n;
wire    skin_and_gray_U0_start_write;
wire    Erode_U0_start_full_n;
wire    Erode_U0_start_write;
wire    Dilate_U0_start_full_n;
wire    Dilate_U0_start_write;
wire    Resize_U0_start_full_n;
wire    Resize_U0_start_write;
wire    compute_real_hog_U0_start_full_n;
wire    compute_real_hog_U0_start_write;

// power-on initialization
initial begin
#0 ap_sync_reg_Block_Mat_exit11_pro_U0_ap_ready = 1'b0;
#0 Block_Mat_exit11_pro_U0_ap_ready_count = 2'd0;
#0 ap_sync_reg_AXIvideo2Mat_U0_ap_ready = 1'b0;
#0 AXIvideo2Mat_U0_ap_ready_count = 2'd0;
#0 ap_sync_reg_compute_real_hog_U0_ap_ready = 1'b0;
#0 compute_real_hog_U0_ap_ready_count = 2'd0;
end

skin_process_accel_ctrl_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
skin_process_accel_ctrl_s_axi_U(
    .AWVALID(s_axi_ctrl_AWVALID),
    .AWREADY(s_axi_ctrl_AWREADY),
    .AWADDR(s_axi_ctrl_AWADDR),
    .WVALID(s_axi_ctrl_WVALID),
    .WREADY(s_axi_ctrl_WREADY),
    .WDATA(s_axi_ctrl_WDATA),
    .WSTRB(s_axi_ctrl_WSTRB),
    .ARVALID(s_axi_ctrl_ARVALID),
    .ARREADY(s_axi_ctrl_ARREADY),
    .ARADDR(s_axi_ctrl_ARADDR),
    .RVALID(s_axi_ctrl_RVALID),
    .RREADY(s_axi_ctrl_RREADY),
    .RDATA(s_axi_ctrl_RDATA),
    .RRESP(s_axi_ctrl_RRESP),
    .BVALID(s_axi_ctrl_BVALID),
    .BREADY(s_axi_ctrl_BREADY),
    .BRESP(s_axi_ctrl_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .hog_features_address0(compute_real_hog_U0_features_address0),
    .hog_features_ce0(compute_real_hog_U0_features_ce0),
    .hog_features_we0(compute_real_hog_U0_features_we0),
    .hog_features_d0(compute_real_hog_U0_features_d0),
    .hog_features_q0(hog_features_q0),
    .rows(rows),
    .cols(cols)
);

Block_Mat_exit11_pro Block_Mat_exit11_pro_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_Mat_exit11_pro_U0_ap_start),
    .start_full_n(Block_Mat_exit11_pro_U0_start_full_n),
    .ap_done(Block_Mat_exit11_pro_U0_ap_done),
    .ap_continue(Block_Mat_exit11_pro_U0_ap_continue),
    .ap_idle(Block_Mat_exit11_pro_U0_ap_idle),
    .ap_ready(Block_Mat_exit11_pro_U0_ap_ready),
    .start_out(Block_Mat_exit11_pro_U0_start_out),
    .start_write(Block_Mat_exit11_pro_U0_start_write),
    .rows(rows),
    .cols(cols),
    .img_rgb_rows_V_out_din(Block_Mat_exit11_pro_U0_img_rgb_rows_V_out_din),
    .img_rgb_rows_V_out_full_n(img_rgb_rows_V_c_full_n),
    .img_rgb_rows_V_out_write(Block_Mat_exit11_pro_U0_img_rgb_rows_V_out_write),
    .img_rgb_cols_V_out_din(Block_Mat_exit11_pro_U0_img_rgb_cols_V_out_din),
    .img_rgb_cols_V_out_full_n(img_rgb_cols_V_c_full_n),
    .img_rgb_cols_V_out_write(Block_Mat_exit11_pro_U0_img_rgb_cols_V_out_write),
    .img_mask_gray_rows_V_out_din(Block_Mat_exit11_pro_U0_img_mask_gray_rows_V_out_din),
    .img_mask_gray_rows_V_out_full_n(img_mask_gray_rows_V_full_n),
    .img_mask_gray_rows_V_out_write(Block_Mat_exit11_pro_U0_img_mask_gray_rows_V_out_write),
    .img_mask_gray_cols_V_out_din(Block_Mat_exit11_pro_U0_img_mask_gray_cols_V_out_din),
    .img_mask_gray_cols_V_out_full_n(img_mask_gray_cols_V_full_n),
    .img_mask_gray_cols_V_out_write(Block_Mat_exit11_pro_U0_img_mask_gray_cols_V_out_write),
    .img_erode_rows_V_out_din(Block_Mat_exit11_pro_U0_img_erode_rows_V_out_din),
    .img_erode_rows_V_out_full_n(img_erode_rows_V_c_full_n),
    .img_erode_rows_V_out_write(Block_Mat_exit11_pro_U0_img_erode_rows_V_out_write),
    .img_erode_cols_V_out_din(Block_Mat_exit11_pro_U0_img_erode_cols_V_out_din),
    .img_erode_cols_V_out_full_n(img_erode_cols_V_c_full_n),
    .img_erode_cols_V_out_write(Block_Mat_exit11_pro_U0_img_erode_cols_V_out_write),
    .img_dilate_rows_V_out_din(Block_Mat_exit11_pro_U0_img_dilate_rows_V_out_din),
    .img_dilate_rows_V_out_full_n(img_dilate_rows_V_c_full_n),
    .img_dilate_rows_V_out_write(Block_Mat_exit11_pro_U0_img_dilate_rows_V_out_write),
    .img_dilate_cols_V_out_din(Block_Mat_exit11_pro_U0_img_dilate_cols_V_out_din),
    .img_dilate_cols_V_out_full_n(img_dilate_cols_V_c_full_n),
    .img_dilate_cols_V_out_write(Block_Mat_exit11_pro_U0_img_dilate_cols_V_out_write)
);

AXIvideo2Mat AXIvideo2Mat_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(AXIvideo2Mat_U0_ap_start),
    .start_full_n(start_for_skin_and_gray_U0_full_n),
    .ap_done(AXIvideo2Mat_U0_ap_done),
    .ap_continue(AXIvideo2Mat_U0_ap_continue),
    .ap_idle(AXIvideo2Mat_U0_ap_idle),
    .ap_ready(AXIvideo2Mat_U0_ap_ready),
    .start_out(AXIvideo2Mat_U0_start_out),
    .start_write(AXIvideo2Mat_U0_start_write),
    .input_stream_TDATA(input_stream_TDATA),
    .input_stream_TVALID(input_stream_TVALID),
    .input_stream_TREADY(AXIvideo2Mat_U0_input_stream_TREADY),
    .input_stream_TKEEP(input_stream_TKEEP),
    .input_stream_TSTRB(input_stream_TSTRB),
    .input_stream_TUSER(input_stream_TUSER),
    .input_stream_TLAST(input_stream_TLAST),
    .input_stream_TID(input_stream_TID),
    .input_stream_TDEST(input_stream_TDEST),
    .img_rows_V_dout(img_rgb_rows_V_c_dout),
    .img_rows_V_empty_n(img_rgb_rows_V_c_empty_n),
    .img_rows_V_read(AXIvideo2Mat_U0_img_rows_V_read),
    .img_cols_V_dout(img_rgb_cols_V_c_dout),
    .img_cols_V_empty_n(img_rgb_cols_V_c_empty_n),
    .img_cols_V_read(AXIvideo2Mat_U0_img_cols_V_read),
    .img_data_stream_0_V_din(AXIvideo2Mat_U0_img_data_stream_0_V_din),
    .img_data_stream_0_V_full_n(img_rgb_data_stream_s_full_n),
    .img_data_stream_0_V_write(AXIvideo2Mat_U0_img_data_stream_0_V_write),
    .img_data_stream_1_V_din(AXIvideo2Mat_U0_img_data_stream_1_V_din),
    .img_data_stream_1_V_full_n(img_rgb_data_stream_1_full_n),
    .img_data_stream_1_V_write(AXIvideo2Mat_U0_img_data_stream_1_V_write),
    .img_data_stream_2_V_din(AXIvideo2Mat_U0_img_data_stream_2_V_din),
    .img_data_stream_2_V_full_n(img_rgb_data_stream_2_full_n),
    .img_data_stream_2_V_write(AXIvideo2Mat_U0_img_data_stream_2_V_write),
    .img_rows_V_out_din(AXIvideo2Mat_U0_img_rows_V_out_din),
    .img_rows_V_out_full_n(img_rgb_rows_V_c25_full_n),
    .img_rows_V_out_write(AXIvideo2Mat_U0_img_rows_V_out_write),
    .img_cols_V_out_din(AXIvideo2Mat_U0_img_cols_V_out_din),
    .img_cols_V_out_full_n(img_rgb_cols_V_c26_full_n),
    .img_cols_V_out_write(AXIvideo2Mat_U0_img_cols_V_out_write)
);

skin_and_gray skin_and_gray_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(skin_and_gray_U0_ap_start),
    .ap_done(skin_and_gray_U0_ap_done),
    .ap_continue(skin_and_gray_U0_ap_continue),
    .ap_idle(skin_and_gray_U0_ap_idle),
    .ap_ready(skin_and_gray_U0_ap_ready),
    .src_rows_V_dout(img_rgb_rows_V_c25_dout),
    .src_rows_V_empty_n(img_rgb_rows_V_c25_empty_n),
    .src_rows_V_read(skin_and_gray_U0_src_rows_V_read),
    .src_cols_V_dout(img_rgb_cols_V_c26_dout),
    .src_cols_V_empty_n(img_rgb_cols_V_c26_empty_n),
    .src_cols_V_read(skin_and_gray_U0_src_cols_V_read),
    .src_data_stream_0_V_dout(img_rgb_data_stream_s_dout),
    .src_data_stream_0_V_empty_n(img_rgb_data_stream_s_empty_n),
    .src_data_stream_0_V_read(skin_and_gray_U0_src_data_stream_0_V_read),
    .src_data_stream_1_V_dout(img_rgb_data_stream_1_dout),
    .src_data_stream_1_V_empty_n(img_rgb_data_stream_1_empty_n),
    .src_data_stream_1_V_read(skin_and_gray_U0_src_data_stream_1_V_read),
    .src_data_stream_2_V_dout(img_rgb_data_stream_2_dout),
    .src_data_stream_2_V_empty_n(img_rgb_data_stream_2_empty_n),
    .src_data_stream_2_V_read(skin_and_gray_U0_src_data_stream_2_V_read),
    .dst_data_stream_V_din(skin_and_gray_U0_dst_data_stream_V_din),
    .dst_data_stream_V_full_n(img_mask_gray_data_s_full_n),
    .dst_data_stream_V_write(skin_and_gray_U0_dst_data_stream_V_write)
);

Erode Erode_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Erode_U0_ap_start),
    .ap_done(Erode_U0_ap_done),
    .ap_continue(Erode_U0_ap_continue),
    .ap_idle(Erode_U0_ap_idle),
    .ap_ready(Erode_U0_ap_ready),
    .p_src_rows_V_dout(img_mask_gray_rows_V_dout),
    .p_src_rows_V_empty_n(img_mask_gray_rows_V_empty_n),
    .p_src_rows_V_read(Erode_U0_p_src_rows_V_read),
    .p_src_cols_V_dout(img_mask_gray_cols_V_dout),
    .p_src_cols_V_empty_n(img_mask_gray_cols_V_empty_n),
    .p_src_cols_V_read(Erode_U0_p_src_cols_V_read),
    .p_src_data_stream_V_dout(img_mask_gray_data_s_dout),
    .p_src_data_stream_V_empty_n(img_mask_gray_data_s_empty_n),
    .p_src_data_stream_V_read(Erode_U0_p_src_data_stream_V_read),
    .p_dst_data_stream_V_din(Erode_U0_p_dst_data_stream_V_din),
    .p_dst_data_stream_V_full_n(img_erode_data_strea_full_n),
    .p_dst_data_stream_V_write(Erode_U0_p_dst_data_stream_V_write)
);

Dilate Dilate_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Dilate_U0_ap_start),
    .ap_done(Dilate_U0_ap_done),
    .ap_continue(Dilate_U0_ap_continue),
    .ap_idle(Dilate_U0_ap_idle),
    .ap_ready(Dilate_U0_ap_ready),
    .p_src_rows_V_dout(img_erode_rows_V_c_dout),
    .p_src_rows_V_empty_n(img_erode_rows_V_c_empty_n),
    .p_src_rows_V_read(Dilate_U0_p_src_rows_V_read),
    .p_src_cols_V_dout(img_erode_cols_V_c_dout),
    .p_src_cols_V_empty_n(img_erode_cols_V_c_empty_n),
    .p_src_cols_V_read(Dilate_U0_p_src_cols_V_read),
    .p_src_data_stream_V_dout(img_erode_data_strea_dout),
    .p_src_data_stream_V_empty_n(img_erode_data_strea_empty_n),
    .p_src_data_stream_V_read(Dilate_U0_p_src_data_stream_V_read),
    .p_dst_data_stream_V_din(Dilate_U0_p_dst_data_stream_V_din),
    .p_dst_data_stream_V_full_n(img_dilate_data_stre_full_n),
    .p_dst_data_stream_V_write(Dilate_U0_p_dst_data_stream_V_write)
);

Resize Resize_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Resize_U0_ap_start),
    .ap_done(Resize_U0_ap_done),
    .ap_continue(Resize_U0_ap_continue),
    .ap_idle(Resize_U0_ap_idle),
    .ap_ready(Resize_U0_ap_ready),
    .p_src_rows_V_dout(img_dilate_rows_V_c_dout),
    .p_src_rows_V_empty_n(img_dilate_rows_V_c_empty_n),
    .p_src_rows_V_read(Resize_U0_p_src_rows_V_read),
    .p_src_cols_V_dout(img_dilate_cols_V_c_dout),
    .p_src_cols_V_empty_n(img_dilate_cols_V_c_empty_n),
    .p_src_cols_V_read(Resize_U0_p_src_cols_V_read),
    .p_src_data_stream_V_dout(img_dilate_data_stre_dout),
    .p_src_data_stream_V_empty_n(img_dilate_data_stre_empty_n),
    .p_src_data_stream_V_read(Resize_U0_p_src_data_stream_V_read),
    .p_dst_data_stream_V_din(Resize_U0_p_dst_data_stream_V_din),
    .p_dst_data_stream_V_full_n(img_resized_data_str_full_n),
    .p_dst_data_stream_V_write(Resize_U0_p_dst_data_stream_V_write)
);

compute_real_hog compute_real_hog_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(compute_real_hog_U0_ap_start),
    .ap_done(compute_real_hog_U0_ap_done),
    .ap_continue(compute_real_hog_U0_ap_continue),
    .ap_idle(compute_real_hog_U0_ap_idle),
    .ap_ready(compute_real_hog_U0_ap_ready),
    .src_data_stream_V_dout(img_resized_data_str_dout),
    .src_data_stream_V_empty_n(img_resized_data_str_empty_n),
    .src_data_stream_V_read(compute_real_hog_U0_src_data_stream_V_read),
    .features_address0(compute_real_hog_U0_features_address0),
    .features_ce0(compute_real_hog_U0_features_ce0),
    .features_we0(compute_real_hog_U0_features_we0),
    .features_d0(compute_real_hog_U0_features_d0),
    .features_q0(hog_features_q0)
);

fifo_w32_d2_A img_rgb_rows_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_Mat_exit11_pro_U0_img_rgb_rows_V_out_din),
    .if_full_n(img_rgb_rows_V_c_full_n),
    .if_write(Block_Mat_exit11_pro_U0_img_rgb_rows_V_out_write),
    .if_dout(img_rgb_rows_V_c_dout),
    .if_empty_n(img_rgb_rows_V_c_empty_n),
    .if_read(AXIvideo2Mat_U0_img_rows_V_read)
);

fifo_w32_d2_A img_rgb_cols_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_Mat_exit11_pro_U0_img_rgb_cols_V_out_din),
    .if_full_n(img_rgb_cols_V_c_full_n),
    .if_write(Block_Mat_exit11_pro_U0_img_rgb_cols_V_out_write),
    .if_dout(img_rgb_cols_V_c_dout),
    .if_empty_n(img_rgb_cols_V_c_empty_n),
    .if_read(AXIvideo2Mat_U0_img_cols_V_read)
);

fifo_w32_d4_A img_mask_gray_rows_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_Mat_exit11_pro_U0_img_mask_gray_rows_V_out_din),
    .if_full_n(img_mask_gray_rows_V_full_n),
    .if_write(Block_Mat_exit11_pro_U0_img_mask_gray_rows_V_out_write),
    .if_dout(img_mask_gray_rows_V_dout),
    .if_empty_n(img_mask_gray_rows_V_empty_n),
    .if_read(Erode_U0_p_src_rows_V_read)
);

fifo_w32_d4_A img_mask_gray_cols_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_Mat_exit11_pro_U0_img_mask_gray_cols_V_out_din),
    .if_full_n(img_mask_gray_cols_V_full_n),
    .if_write(Block_Mat_exit11_pro_U0_img_mask_gray_cols_V_out_write),
    .if_dout(img_mask_gray_cols_V_dout),
    .if_empty_n(img_mask_gray_cols_V_empty_n),
    .if_read(Erode_U0_p_src_cols_V_read)
);

fifo_w32_d5_A img_erode_rows_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_Mat_exit11_pro_U0_img_erode_rows_V_out_din),
    .if_full_n(img_erode_rows_V_c_full_n),
    .if_write(Block_Mat_exit11_pro_U0_img_erode_rows_V_out_write),
    .if_dout(img_erode_rows_V_c_dout),
    .if_empty_n(img_erode_rows_V_c_empty_n),
    .if_read(Dilate_U0_p_src_rows_V_read)
);

fifo_w32_d5_A img_erode_cols_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_Mat_exit11_pro_U0_img_erode_cols_V_out_din),
    .if_full_n(img_erode_cols_V_c_full_n),
    .if_write(Block_Mat_exit11_pro_U0_img_erode_cols_V_out_write),
    .if_dout(img_erode_cols_V_c_dout),
    .if_empty_n(img_erode_cols_V_c_empty_n),
    .if_read(Dilate_U0_p_src_cols_V_read)
);

fifo_w32_d6_A img_dilate_rows_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_Mat_exit11_pro_U0_img_dilate_rows_V_out_din),
    .if_full_n(img_dilate_rows_V_c_full_n),
    .if_write(Block_Mat_exit11_pro_U0_img_dilate_rows_V_out_write),
    .if_dout(img_dilate_rows_V_c_dout),
    .if_empty_n(img_dilate_rows_V_c_empty_n),
    .if_read(Resize_U0_p_src_rows_V_read)
);

fifo_w32_d6_A img_dilate_cols_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_Mat_exit11_pro_U0_img_dilate_cols_V_out_din),
    .if_full_n(img_dilate_cols_V_c_full_n),
    .if_write(Block_Mat_exit11_pro_U0_img_dilate_cols_V_out_write),
    .if_dout(img_dilate_cols_V_c_dout),
    .if_empty_n(img_dilate_cols_V_c_empty_n),
    .if_read(Resize_U0_p_src_cols_V_read)
);

fifo_w8_d2_A img_rgb_data_stream_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_data_stream_0_V_din),
    .if_full_n(img_rgb_data_stream_s_full_n),
    .if_write(AXIvideo2Mat_U0_img_data_stream_0_V_write),
    .if_dout(img_rgb_data_stream_s_dout),
    .if_empty_n(img_rgb_data_stream_s_empty_n),
    .if_read(skin_and_gray_U0_src_data_stream_0_V_read)
);

fifo_w8_d2_A img_rgb_data_stream_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_data_stream_1_V_din),
    .if_full_n(img_rgb_data_stream_1_full_n),
    .if_write(AXIvideo2Mat_U0_img_data_stream_1_V_write),
    .if_dout(img_rgb_data_stream_1_dout),
    .if_empty_n(img_rgb_data_stream_1_empty_n),
    .if_read(skin_and_gray_U0_src_data_stream_1_V_read)
);

fifo_w8_d2_A img_rgb_data_stream_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_data_stream_2_V_din),
    .if_full_n(img_rgb_data_stream_2_full_n),
    .if_write(AXIvideo2Mat_U0_img_data_stream_2_V_write),
    .if_dout(img_rgb_data_stream_2_dout),
    .if_empty_n(img_rgb_data_stream_2_empty_n),
    .if_read(skin_and_gray_U0_src_data_stream_2_V_read)
);

fifo_w32_d2_A img_rgb_rows_V_c25_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_rows_V_out_din),
    .if_full_n(img_rgb_rows_V_c25_full_n),
    .if_write(AXIvideo2Mat_U0_img_rows_V_out_write),
    .if_dout(img_rgb_rows_V_c25_dout),
    .if_empty_n(img_rgb_rows_V_c25_empty_n),
    .if_read(skin_and_gray_U0_src_rows_V_read)
);

fifo_w32_d2_A img_rgb_cols_V_c26_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_cols_V_out_din),
    .if_full_n(img_rgb_cols_V_c26_full_n),
    .if_write(AXIvideo2Mat_U0_img_cols_V_out_write),
    .if_dout(img_rgb_cols_V_c26_dout),
    .if_empty_n(img_rgb_cols_V_c26_empty_n),
    .if_read(skin_and_gray_U0_src_cols_V_read)
);

fifo_w8_d2_A img_mask_gray_data_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(skin_and_gray_U0_dst_data_stream_V_din),
    .if_full_n(img_mask_gray_data_s_full_n),
    .if_write(skin_and_gray_U0_dst_data_stream_V_write),
    .if_dout(img_mask_gray_data_s_dout),
    .if_empty_n(img_mask_gray_data_s_empty_n),
    .if_read(Erode_U0_p_src_data_stream_V_read)
);

fifo_w8_d2_A img_erode_data_strea_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Erode_U0_p_dst_data_stream_V_din),
    .if_full_n(img_erode_data_strea_full_n),
    .if_write(Erode_U0_p_dst_data_stream_V_write),
    .if_dout(img_erode_data_strea_dout),
    .if_empty_n(img_erode_data_strea_empty_n),
    .if_read(Dilate_U0_p_src_data_stream_V_read)
);

fifo_w8_d2_A img_dilate_data_stre_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Dilate_U0_p_dst_data_stream_V_din),
    .if_full_n(img_dilate_data_stre_full_n),
    .if_write(Dilate_U0_p_dst_data_stream_V_write),
    .if_dout(img_dilate_data_stre_dout),
    .if_empty_n(img_dilate_data_stre_empty_n),
    .if_read(Resize_U0_p_src_data_stream_V_read)
);

fifo_w8_d2_A img_resized_data_str_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Resize_U0_p_dst_data_stream_V_din),
    .if_full_n(img_resized_data_str_full_n),
    .if_write(Resize_U0_p_dst_data_stream_V_write),
    .if_dout(img_resized_data_str_dout),
    .if_empty_n(img_resized_data_str_empty_n),
    .if_read(compute_real_hog_U0_src_data_stream_V_read)
);

start_for_Erode_U0 start_for_Erode_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Erode_U0_din),
    .if_full_n(start_for_Erode_U0_full_n),
    .if_write(Block_Mat_exit11_pro_U0_start_write),
    .if_dout(start_for_Erode_U0_dout),
    .if_empty_n(start_for_Erode_U0_empty_n),
    .if_read(Erode_U0_ap_ready)
);

start_for_Dilate_U0 start_for_Dilate_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Dilate_U0_din),
    .if_full_n(start_for_Dilate_U0_full_n),
    .if_write(Block_Mat_exit11_pro_U0_start_write),
    .if_dout(start_for_Dilate_U0_dout),
    .if_empty_n(start_for_Dilate_U0_empty_n),
    .if_read(Dilate_U0_ap_ready)
);

start_for_Resize_U0 start_for_Resize_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Resize_U0_din),
    .if_full_n(start_for_Resize_U0_full_n),
    .if_write(Block_Mat_exit11_pro_U0_start_write),
    .if_dout(start_for_Resize_U0_dout),
    .if_empty_n(start_for_Resize_U0_empty_n),
    .if_read(Resize_U0_ap_ready)
);

start_for_skin_anDeQ start_for_skin_anDeQ_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_skin_and_gray_U0_din),
    .if_full_n(start_for_skin_and_gray_U0_full_n),
    .if_write(AXIvideo2Mat_U0_start_write),
    .if_dout(start_for_skin_and_gray_U0_dout),
    .if_empty_n(start_for_skin_and_gray_U0_empty_n),
    .if_read(skin_and_gray_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_AXIvideo2Mat_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_AXIvideo2Mat_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_AXIvideo2Mat_U0_ap_ready <= ap_sync_AXIvideo2Mat_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Block_Mat_exit11_pro_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Block_Mat_exit11_pro_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Block_Mat_exit11_pro_U0_ap_ready <= ap_sync_Block_Mat_exit11_pro_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_compute_real_hog_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_compute_real_hog_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_compute_real_hog_U0_ap_ready <= ap_sync_compute_real_hog_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_sync_ready == 1'b1) & (1'b0 == AXIvideo2Mat_U0_ap_ready))) begin
        AXIvideo2Mat_U0_ap_ready_count <= (AXIvideo2Mat_U0_ap_ready_count - 2'd1);
    end else if (((ap_sync_ready == 1'b0) & (1'b1 == AXIvideo2Mat_U0_ap_ready))) begin
        AXIvideo2Mat_U0_ap_ready_count <= (AXIvideo2Mat_U0_ap_ready_count + 2'd1);
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == Block_Mat_exit11_pro_U0_ap_ready) & (ap_sync_ready == 1'b1))) begin
        Block_Mat_exit11_pro_U0_ap_ready_count <= (Block_Mat_exit11_pro_U0_ap_ready_count - 2'd1);
    end else if (((ap_sync_ready == 1'b0) & (1'b1 == Block_Mat_exit11_pro_U0_ap_ready))) begin
        Block_Mat_exit11_pro_U0_ap_ready_count <= (Block_Mat_exit11_pro_U0_ap_ready_count + 2'd1);
    end
end

always @ (posedge ap_clk) begin
    if (((ap_sync_ready == 1'b1) & (compute_real_hog_U0_ap_ready == 1'b0))) begin
        compute_real_hog_U0_ap_ready_count <= (compute_real_hog_U0_ap_ready_count - 2'd1);
    end else if (((ap_sync_ready == 1'b0) & (compute_real_hog_U0_ap_ready == 1'b1))) begin
        compute_real_hog_U0_ap_ready_count <= (compute_real_hog_U0_ap_ready_count + 2'd1);
    end
end

assign AXIvideo2Mat_U0_ap_continue = 1'b1;

assign AXIvideo2Mat_U0_ap_start = ((ap_sync_reg_AXIvideo2Mat_U0_ap_ready ^ 1'b1) & ap_start);

assign Block_Mat_exit11_pro_U0_ap_continue = 1'b1;

assign Block_Mat_exit11_pro_U0_ap_start = ((ap_sync_reg_Block_Mat_exit11_pro_U0_ap_ready ^ 1'b1) & ap_start);

assign Block_Mat_exit11_pro_U0_start_full_n = (start_for_Resize_U0_full_n & start_for_Erode_U0_full_n & start_for_Dilate_U0_full_n);

assign Dilate_U0_ap_continue = 1'b1;

assign Dilate_U0_ap_start = start_for_Dilate_U0_empty_n;

assign Dilate_U0_start_full_n = 1'b1;

assign Dilate_U0_start_write = 1'b0;

assign Erode_U0_ap_continue = 1'b1;

assign Erode_U0_ap_start = start_for_Erode_U0_empty_n;

assign Erode_U0_start_full_n = 1'b1;

assign Erode_U0_start_write = 1'b0;

assign Resize_U0_ap_continue = 1'b1;

assign Resize_U0_ap_start = start_for_Resize_U0_empty_n;

assign Resize_U0_start_full_n = 1'b1;

assign Resize_U0_start_write = 1'b0;

assign ap_done = compute_real_hog_U0_ap_done;

assign ap_idle = (skin_and_gray_U0_ap_idle & compute_real_hog_U0_ap_idle & Resize_U0_ap_idle & Erode_U0_ap_idle & Dilate_U0_ap_idle & Block_Mat_exit11_pro_U0_ap_idle & AXIvideo2Mat_U0_ap_idle);

assign ap_ready = ap_sync_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_AXIvideo2Mat_U0_ap_ready = (ap_sync_reg_AXIvideo2Mat_U0_ap_ready | AXIvideo2Mat_U0_ap_ready);

assign ap_sync_Block_Mat_exit11_pro_U0_ap_ready = (ap_sync_reg_Block_Mat_exit11_pro_U0_ap_ready | Block_Mat_exit11_pro_U0_ap_ready);

assign ap_sync_compute_real_hog_U0_ap_ready = (compute_real_hog_U0_ap_ready | ap_sync_reg_compute_real_hog_U0_ap_ready);

assign ap_sync_continue = 1'b1;

assign ap_sync_done = compute_real_hog_U0_ap_done;

assign ap_sync_ready = (ap_sync_compute_real_hog_U0_ap_ready & ap_sync_Block_Mat_exit11_pro_U0_ap_ready & ap_sync_AXIvideo2Mat_U0_ap_ready);

assign compute_real_hog_U0_ap_continue = 1'b1;

assign compute_real_hog_U0_ap_start = ((ap_sync_reg_compute_real_hog_U0_ap_ready ^ 1'b1) & ap_start);

assign compute_real_hog_U0_start_full_n = 1'b1;

assign compute_real_hog_U0_start_write = 1'b0;

assign input_stream_TREADY = AXIvideo2Mat_U0_input_stream_TREADY;

assign skin_and_gray_U0_ap_continue = 1'b1;

assign skin_and_gray_U0_ap_start = start_for_skin_and_gray_U0_empty_n;

assign skin_and_gray_U0_start_full_n = 1'b1;

assign skin_and_gray_U0_start_write = 1'b0;

assign start_for_Dilate_U0_din = 1'b1;

assign start_for_Erode_U0_din = 1'b1;

assign start_for_Resize_U0_din = 1'b1;

assign start_for_skin_and_gray_U0_din = 1'b1;

endmodule //skin_process_accel
