# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "F:/vivado_project/M3_t/M3_test/.Xil/Vivado-12780-LAPTOP-A50L20VJ/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a100tcsg324-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/ea75/rtl
    f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/4fba
    f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/ec67/hdl
  } {
      F:/vivado/Vivado/2019.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      F:/vivado/Vivado/2019.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      F:/vivado/Vivado/2019.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/ea75/rtl
    f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/4fba
    f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/ec67/hdl
  } {
      F:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/new/swdio_tri_buffer.v
      F:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/new/axis_colorbar.v
      F:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/new/rgb888_to_rgb444_vga.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/ea75/rtl/cm3_dap_ahb_ap.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/ea75/rtl/cm3_wic.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/ea75/rtl/cm3_nvic.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/ea75/rtl/cm3_dwt.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/ea75/rtl/AhbToAxi.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/ea75/rtl/cm3_mpu.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/ea75/rtl/cm3_bus_matrix.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/ea75/rtl/models.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/ea75/rtl/cmsdk.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/ea75/rtl/cm3_tpiu.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/ea75/rtl/dapswjdp.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/ea75/rtl/cm3_fpb.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/ea75/rtl/cm3_dpu.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/ea75/rtl/cm3_itm.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/ea75/rtl/cm3_etm.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/ea75/rtl/cortexm3.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/ea75/rtl/cortexm3_integration.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_CORTEXM3_AXI_0_0/synth/design_1_CORTEXM3_AXI_0_0.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_clk_wiz.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_util_vector_logic_0_0/synth/design_1_util_vector_logic_0_0.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/34f7/hdl/xlconstant_v1_1_vl_rfs.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_xlconstant_0_0/synth/design_1_xlconstant_0_0.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_xlconstant_1_0/synth/design_1_xlconstant_1_0.v
      F:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/synth/design_1.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_swdio_tri_buffer_0_0/synth/design_1_swdio_tri_buffer_0_0.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/72d4/hdl/axi_register_slice_v2_1_vl_rfs.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/60de/hdl/axi_data_fifo_v2_1_vl_rfs.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/6b0d/hdl/axi_crossbar_v2_1_vl_rfs.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/synth/design_1_xbar_0.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/a87e/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_v_axi4s_vid_out_0_0/synth/design_1_v_axi4s_vid_out_0_0.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_xlconstant_2_0/synth/design_1_xlconstant_2_0.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_util_vector_logic_0_2/synth/design_1_util_vector_logic_0_2.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_xlconstant_3_0/synth/design_1_xlconstant_3_0.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_axis_colorbar_0_0/synth/design_1_axis_colorbar_0_0.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_rgb888_to_rgb444_vga_0_0/synth/design_1_rgb888_to_rgb444_vga_0_0.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/c4a6/hdl/axi_protocol_converter_v2_1_vl_rfs.v
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/synth/design_1_auto_pc_0.v
      F:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
    }
      rt::read_vhdl -lib lib_cdc_v1_0_2 f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_13 f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib {
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/synth/design_1_proc_sys_reset_0_0.vhd
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/synth/design_1_axi_gpio_0_0.vhd
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/synth/design_1_axi_uartlite_0_0.vhd
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_1/synth/design_1_proc_sys_reset_0_1.vhd
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_2/synth/design_1_proc_sys_reset_0_2.vhd
      f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_v_tc_0_0/synth/design_1_v_tc_0_0.vhd
    }
      rt::read_vhdl -lib axi_lite_ipif_v3_0_4 f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib interrupt_control_v3_1_4 f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd
      rt::read_vhdl -lib axi_gpio_v2_0_22 f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/f71e/hdl/axi_gpio_v2_0_vh_rfs.vhd
      rt::read_vhdl -lib blk_mem_gen_v8_4_4 f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/2985/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::read_vhdl -lib fifo_generator_v13_2_5 f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/276e/hdl/fifo_generator_v13_2_vhsyn_rfs.vhd
      rt::read_vhdl -lib lib_pkg_v1_0_2 f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd
      rt::read_vhdl -lib lib_srl_fifo_v1_0_2 f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd
      rt::read_vhdl -lib axi_uartlite_v2_0_24 f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/d8db/hdl/axi_uartlite_v2_0_vh_rfs.vhd
      rt::read_vhdl -lib v_tc_v6_2_0 f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ipshared/111e/hdl/v_tc_v6_2_vh_rfs.vhd
      rt::read_vhdl -lib xpm F:/vivado/Vivado/2019.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top design_1_wrapper
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "F:/vivado_project/M3_t/M3_test/.Xil/Vivado-12780-LAPTOP-A50L20VJ/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
