// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module addsub (
        ap_ready,
        a_V,
        b_V,
        add,
        ap_return
);


output   ap_ready;
input  [42:0] a_V;
input  [42:0] b_V;
input   add;
output  [43:0] ap_return;

wire  signed [43:0] lhs_V_fu_34_p1;
wire  signed [43:0] rhs_V_fu_38_p1;
wire   [0:0] ret_V_12_fu_54_p0;
wire   [43:0] ret_V_fu_48_p2;
wire   [43:0] ret_V_10_fu_42_p2;

assign ap_ready = 1'b1;

assign ap_return = ((ret_V_12_fu_54_p0[0:0] === 1'b1) ? ret_V_fu_48_p2 : ret_V_10_fu_42_p2);

assign lhs_V_fu_34_p1 = $signed(a_V);

assign ret_V_10_fu_42_p2 = ($signed(lhs_V_fu_34_p1) - $signed(rhs_V_fu_38_p1));

assign ret_V_12_fu_54_p0 = add;

assign ret_V_fu_48_p2 = ($signed(rhs_V_fu_38_p1) + $signed(lhs_V_fu_34_p1));

assign rhs_V_fu_38_p1 = $signed(b_V);

endmodule //addsub
