// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Dilate_0_0_48_48_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_src_data_stream_V_dout,
        p_src_data_stream_V_empty_n,
        p_src_data_stream_V_read,
        p_dst_data_stream_V_din,
        p_dst_data_stream_V_full_n,
        p_dst_data_stream_V_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state8 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] p_src_data_stream_V_dout;
input   p_src_data_stream_V_empty_n;
output   p_src_data_stream_V_read;
output  [7:0] p_dst_data_stream_V_din;
input   p_dst_data_stream_V_full_n;
output   p_dst_data_stream_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_V_read;
reg p_dst_data_stream_V_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_src_data_stream_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] and_ln118_reg_821;
reg   [0:0] icmp_ln899_reg_783;
reg   [0:0] icmp_ln887_reg_774;
reg    p_dst_data_stream_V_blk_n;
reg    ap_enable_reg_pp0_iter4;
reg   [0:0] and_ln512_reg_855;
reg   [0:0] and_ln512_reg_855_pp0_iter3_reg;
reg   [5:0] t_V_5_reg_235;
wire   [0:0] icmp_ln443_fu_246_p2;
wire    ap_CS_fsm_state2;
wire   [5:0] i_V_fu_252_p2;
reg   [5:0] i_V_reg_769;
wire   [0:0] icmp_ln887_fu_258_p2;
wire   [0:0] xor_ln457_fu_264_p2;
reg   [0:0] xor_ln457_reg_778;
wire   [0:0] icmp_ln899_fu_280_p2;
wire   [0:0] icmp_ln879_fu_286_p2;
reg   [0:0] icmp_ln879_reg_788;
wire   [0:0] icmp_ln879_2_fu_292_p2;
reg   [0:0] icmp_ln879_2_reg_792;
wire   [0:0] icmp_ln899_2_fu_298_p2;
reg   [0:0] icmp_ln899_2_reg_796;
wire   [1:0] xor_ln493_fu_308_p2;
reg   [1:0] xor_ln493_reg_802;
wire   [1:0] sub_ln493_fu_314_p2;
reg   [1:0] sub_ln493_reg_807;
wire   [0:0] icmp_ln444_fu_324_p2;
reg   [0:0] icmp_ln444_reg_812;
wire    ap_block_state3_pp0_stage0_iter0;
reg    ap_predicate_op91_read_state4;
reg    ap_predicate_op99_read_state4;
reg    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state6_pp0_stage0_iter3;
reg    ap_block_state7_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln444_reg_812_pp0_iter1_reg;
reg   [0:0] icmp_ln444_reg_812_pp0_iter2_reg;
wire   [5:0] j_V_fu_330_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] and_ln118_fu_378_p2;
wire   [1:0] trunc_ln458_fu_408_p1;
reg   [1:0] trunc_ln458_reg_825;
wire   [0:0] or_ln457_fu_412_p2;
reg   [0:0] or_ln457_reg_830;
reg   [5:0] k_buf_0_val_3_addr_reg_837;
reg   [5:0] k_buf_0_val_4_addr_reg_843;
reg   [5:0] k_buf_0_val_5_addr_reg_849;
wire   [0:0] and_ln512_fu_424_p2;
reg   [0:0] and_ln512_reg_855_pp0_iter1_reg;
reg   [0:0] and_ln512_reg_855_pp0_iter2_reg;
wire   [7:0] col_buf_0_val_0_0_fu_455_p3;
reg   [7:0] col_buf_0_val_0_0_reg_859;
reg   [7:0] col_buf_0_val_0_0_reg_859_pp0_iter2_reg;
wire   [7:0] src_kernel_win_0_va_26_fu_526_p3;
reg   [7:0] src_kernel_win_0_va_26_reg_866;
wire   [7:0] src_kernel_win_0_va_27_fu_544_p3;
reg   [7:0] src_kernel_win_0_va_27_reg_873;
wire   [7:0] select_ln188_fu_563_p3;
reg   [7:0] select_ln188_reg_879;
wire   [0:0] icmp_ln188_1_fu_571_p2;
reg   [0:0] icmp_ln188_1_reg_884;
wire   [7:0] select_ln188_4_fu_621_p3;
reg   [7:0] select_ln188_4_reg_889;
wire   [7:0] tmp_151_fu_689_p3;
reg   [7:0] tmp_151_reg_895;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
wire   [5:0] k_buf_0_val_3_address0;
reg    k_buf_0_val_3_ce0;
wire   [7:0] k_buf_0_val_3_q0;
wire   [5:0] k_buf_0_val_3_address1;
reg    k_buf_0_val_3_ce1;
reg    k_buf_0_val_3_we1;
wire   [5:0] k_buf_0_val_4_address0;
reg    k_buf_0_val_4_ce0;
wire   [7:0] k_buf_0_val_4_q0;
wire   [5:0] k_buf_0_val_4_address1;
reg    k_buf_0_val_4_ce1;
reg    k_buf_0_val_4_we1;
reg   [7:0] k_buf_0_val_4_d1;
wire   [5:0] k_buf_0_val_5_address0;
reg    k_buf_0_val_5_ce0;
wire   [7:0] k_buf_0_val_5_q0;
wire   [5:0] k_buf_0_val_5_address1;
reg    k_buf_0_val_5_ce1;
reg    k_buf_0_val_5_we1;
reg   [7:0] k_buf_0_val_5_d1;
reg   [5:0] t_V_reg_224;
reg    ap_block_state1;
wire    ap_CS_fsm_state8;
wire   [63:0] zext_ln835_fu_417_p1;
reg   [7:0] src_kernel_win_0_va_fu_110;
reg   [7:0] src_kernel_win_0_va_19_fu_114;
reg   [7:0] src_kernel_win_0_va_20_fu_118;
reg   [7:0] src_kernel_win_0_va_21_fu_122;
reg   [7:0] src_kernel_win_0_va_22_fu_126;
reg   [7:0] ap_sig_allocacmp_src_kernel_win_0_va_32;
reg   [7:0] src_kernel_win_0_va_23_fu_130;
reg   [7:0] ap_sig_allocacmp_src_kernel_win_0_va_33;
reg   [7:0] src_kernel_win_0_va_24_fu_134;
reg   [7:0] right_border_buf_0_s_fu_138;
wire   [7:0] col_buf_0_val_2_0_fu_493_p3;
reg   [7:0] right_border_buf_0_4_fu_142;
wire   [7:0] col_buf_0_val_1_0_fu_474_p3;
reg    ap_block_pp0_stage0_01001;
wire   [4:0] tmp_fu_270_p4;
wire   [1:0] trunc_ln506_fu_304_p1;
wire   [4:0] tmp_146_fu_336_p4;
wire   [6:0] zext_ln444_fu_320_p1;
wire   [6:0] ImagLoc_x_fu_352_p2;
wire   [0:0] tmp_147_fu_358_p3;
wire   [0:0] icmp_ln118_fu_372_p2;
wire   [0:0] xor_ln118_fu_366_p2;
wire   [0:0] tmp_148_fu_384_p3;
wire   [6:0] select_ln121_fu_392_p3;
wire   [6:0] x_fu_400_p3;
wire   [0:0] icmp_ln891_fu_346_p2;
wire   [1:0] xor_ln493_2_fu_438_p2;
wire   [7:0] tmp_16_fu_443_p5;
wire   [7:0] tmp_17_fu_462_p5;
wire   [7:0] tmp_18_fu_481_p5;
wire   [7:0] tmp_19_fu_515_p5;
wire   [7:0] tmp_20_fu_533_p5;
wire   [0:0] icmp_ln188_fu_557_p2;
wire   [7:0] select_ln188_1_fu_583_p3;
wire   [0:0] icmp_ln188_2_fu_588_p2;
wire   [7:0] select_ln188_2_fu_594_p3;
wire   [0:0] icmp_ln188_3_fu_602_p2;
wire   [7:0] select_ln188_3_fu_608_p3;
wire   [0:0] icmp_ln188_4_fu_616_p2;
wire   [0:0] icmp_ln188_5_fu_658_p2;
wire   [7:0] select_ln188_5_fu_663_p3;
wire   [0:0] icmp_ln188_6_fu_670_p2;
wire   [7:0] select_ln188_6_fu_676_p3;
wire   [0:0] icmp_ln188_7_fu_684_p2;
reg   [3:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_enable_operation_65;
reg    ap_enable_state3_pp0_iter0_stage0;
wire    ap_enable_operation_81;
reg    ap_enable_state4_pp0_iter1_stage0;
reg    ap_predicate_op95_store_state4;
reg    ap_enable_operation_95;
reg    ap_predicate_op100_store_state4;
reg    ap_enable_operation_100;
reg    ap_enable_operation_67;
wire    ap_enable_operation_85;
reg    ap_predicate_op93_store_state4;
reg    ap_enable_operation_93;
reg    ap_predicate_op98_store_state4;
reg    ap_enable_operation_98;
reg    ap_enable_operation_69;
wire    ap_enable_operation_88;
reg    ap_predicate_op92_store_state4;
reg    ap_enable_operation_92;
reg    ap_predicate_op97_store_state4;
reg    ap_enable_operation_97;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_630;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
end

Erode_0_0_48_48_ssc4 #(
    .DataWidth( 8 ),
    .AddressRange( 48 ),
    .AddressWidth( 6 ))
k_buf_0_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_3_address0),
    .ce0(k_buf_0_val_3_ce0),
    .q0(k_buf_0_val_3_q0),
    .address1(k_buf_0_val_3_address1),
    .ce1(k_buf_0_val_3_ce1),
    .we1(k_buf_0_val_3_we1),
    .d1(p_src_data_stream_V_dout)
);

Erode_0_0_48_48_ssc4 #(
    .DataWidth( 8 ),
    .AddressRange( 48 ),
    .AddressWidth( 6 ))
k_buf_0_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_4_address0),
    .ce0(k_buf_0_val_4_ce0),
    .q0(k_buf_0_val_4_q0),
    .address1(k_buf_0_val_4_address1),
    .ce1(k_buf_0_val_4_ce1),
    .we1(k_buf_0_val_4_we1),
    .d1(k_buf_0_val_4_d1)
);

Erode_0_0_48_48_ssc4 #(
    .DataWidth( 8 ),
    .AddressRange( 48 ),
    .AddressWidth( 6 ))
k_buf_0_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_5_address0),
    .ce0(k_buf_0_val_5_ce0),
    .q0(k_buf_0_val_5_q0),
    .address1(k_buf_0_val_5_address1),
    .ce1(k_buf_0_val_5_ce1),
    .we1(k_buf_0_val_5_we1),
    .d1(k_buf_0_val_5_d1)
);

skin_process_accevdy #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
skin_process_accevdy_U93(
    .din0(src_kernel_win_0_va_24_fu_134),
    .din1(8'd0),
    .din2(8'd0),
    .din3(xor_ln493_2_fu_438_p2),
    .dout(tmp_16_fu_443_p5)
);

skin_process_accevdy #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
skin_process_accevdy_U94(
    .din0(right_border_buf_0_4_fu_142),
    .din1(8'd0),
    .din2(8'd0),
    .din3(xor_ln493_2_fu_438_p2),
    .dout(tmp_17_fu_462_p5)
);

skin_process_accevdy #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
skin_process_accevdy_U95(
    .din0(right_border_buf_0_s_fu_138),
    .din1(8'd0),
    .din2(8'd0),
    .din3(xor_ln493_2_fu_438_p2),
    .dout(tmp_18_fu_481_p5)
);

skin_process_accevdy #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
skin_process_accevdy_U96(
    .din0(col_buf_0_val_0_0_fu_455_p3),
    .din1(col_buf_0_val_1_0_fu_474_p3),
    .din2(col_buf_0_val_2_0_fu_493_p3),
    .din3(xor_ln493_reg_802),
    .dout(tmp_19_fu_515_p5)
);

skin_process_accevdy #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
skin_process_accevdy_U97(
    .din0(col_buf_0_val_0_0_fu_455_p3),
    .din1(col_buf_0_val_1_0_fu_474_p3),
    .din2(col_buf_0_val_2_0_fu_493_p3),
    .din3(sub_ln493_reg_807),
    .dout(tmp_20_fu_533_p5)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln443_fu_246_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((icmp_ln443_fu_246_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state3)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end else if (((icmp_ln443_fu_246_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln444_fu_324_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        t_V_5_reg_235 <= j_V_fu_330_p2;
    end else if (((icmp_ln443_fu_246_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        t_V_5_reg_235 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        t_V_reg_224 <= i_V_reg_769;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        t_V_reg_224 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln444_fu_324_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln118_reg_821 <= and_ln118_fu_378_p2;
        and_ln512_reg_855 <= and_ln512_fu_424_p2;
        k_buf_0_val_3_addr_reg_837 <= zext_ln835_fu_417_p1;
        k_buf_0_val_4_addr_reg_843 <= zext_ln835_fu_417_p1;
        k_buf_0_val_5_addr_reg_849 <= zext_ln835_fu_417_p1;
        or_ln457_reg_830 <= or_ln457_fu_412_p2;
        trunc_ln458_reg_825 <= trunc_ln458_fu_408_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln512_reg_855_pp0_iter1_reg <= and_ln512_reg_855;
        col_buf_0_val_0_0_reg_859 <= col_buf_0_val_0_0_fu_455_p3;
        icmp_ln444_reg_812 <= icmp_ln444_fu_324_p2;
        icmp_ln444_reg_812_pp0_iter1_reg <= icmp_ln444_reg_812;
        src_kernel_win_0_va_26_reg_866 <= src_kernel_win_0_va_26_fu_526_p3;
        src_kernel_win_0_va_27_reg_873 <= src_kernel_win_0_va_27_fu_544_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        and_ln512_reg_855_pp0_iter2_reg <= and_ln512_reg_855_pp0_iter1_reg;
        and_ln512_reg_855_pp0_iter3_reg <= and_ln512_reg_855_pp0_iter2_reg;
        col_buf_0_val_0_0_reg_859_pp0_iter2_reg <= col_buf_0_val_0_0_reg_859;
        icmp_ln444_reg_812_pp0_iter2_reg <= icmp_ln444_reg_812_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_V_reg_769 <= i_V_fu_252_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln512_reg_855) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln188_1_reg_884 <= icmp_ln188_1_fu_571_p2;
        select_ln188_reg_879 <= select_ln188_fu_563_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln443_fu_246_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        icmp_ln879_2_reg_792 <= icmp_ln879_2_fu_292_p2;
        icmp_ln879_reg_788 <= icmp_ln879_fu_286_p2;
        icmp_ln887_reg_774 <= icmp_ln887_fu_258_p2;
        icmp_ln899_2_reg_796 <= icmp_ln899_2_fu_298_p2;
        icmp_ln899_reg_783 <= icmp_ln899_fu_280_p2;
        sub_ln493_reg_807 <= sub_ln493_fu_314_p2;
        xor_ln457_reg_778 <= xor_ln457_fu_264_p2;
        xor_ln493_reg_802 <= xor_ln493_fu_308_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln887_reg_774 == 1'd1) & (icmp_ln899_reg_783 == 1'd1) & (1'd1 == and_ln118_reg_821) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        right_border_buf_0_4_fu_142 <= col_buf_0_val_1_0_fu_474_p3;
        right_border_buf_0_s_fu_138 <= col_buf_0_val_2_0_fu_493_p3;
        src_kernel_win_0_va_24_fu_134 <= col_buf_0_val_0_0_fu_455_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln512_reg_855_pp0_iter1_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        select_ln188_4_reg_889 <= select_ln188_4_fu_621_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln444_reg_812_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_19_fu_114 <= src_kernel_win_0_va_fu_110;
        src_kernel_win_0_va_fu_110 <= col_buf_0_val_0_0_reg_859_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln444_reg_812_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_20_fu_118 <= src_kernel_win_0_va_26_reg_866;
        src_kernel_win_0_va_21_fu_122 <= src_kernel_win_0_va_20_fu_118;
        src_kernel_win_0_va_22_fu_126 <= src_kernel_win_0_va_27_reg_873;
        src_kernel_win_0_va_23_fu_130 <= src_kernel_win_0_va_22_fu_126;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln512_reg_855_pp0_iter2_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_151_reg_895 <= tmp_151_fu_689_p3;
    end
end

always @ (*) begin
    if ((icmp_ln444_fu_324_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln443_fu_246_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln443_fu_246_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln444_reg_812_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_src_kernel_win_0_va_32 = src_kernel_win_0_va_27_reg_873;
    end else begin
        ap_sig_allocacmp_src_kernel_win_0_va_32 = src_kernel_win_0_va_22_fu_126;
    end
end

always @ (*) begin
    if (((icmp_ln444_reg_812_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_src_kernel_win_0_va_33 = src_kernel_win_0_va_22_fu_126;
    end else begin
        ap_sig_allocacmp_src_kernel_win_0_va_33 = src_kernel_win_0_va_23_fu_130;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_3_ce0 = 1'b1;
    end else begin
        k_buf_0_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln887_reg_774 == 1'd1) & (icmp_ln899_reg_783 == 1'd1) & (1'd1 == and_ln118_reg_821) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((icmp_ln899_reg_783 == 1'd0) & (icmp_ln879_2_reg_792 == 1'd1) & (1'd1 == and_ln118_reg_821) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_3_ce1 = 1'b1;
    end else begin
        k_buf_0_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln887_reg_774 == 1'd1) & (icmp_ln899_reg_783 == 1'd1) & (1'd1 == and_ln118_reg_821) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((icmp_ln899_reg_783 == 1'd0) & (icmp_ln879_2_reg_792 == 1'd1) & (1'd1 == and_ln118_reg_821) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_3_we1 = 1'b1;
    end else begin
        k_buf_0_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_4_ce0 = 1'b1;
    end else begin
        k_buf_0_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln887_reg_774 == 1'd1) & (icmp_ln899_reg_783 == 1'd1) & (1'd1 == and_ln118_reg_821) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((icmp_ln899_reg_783 == 1'd0) & (icmp_ln879_reg_788 == 1'd1) & (1'd1 == and_ln118_reg_821) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_4_ce1 = 1'b1;
    end else begin
        k_buf_0_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_630)) begin
        if (((icmp_ln887_reg_774 == 1'd1) & (icmp_ln899_reg_783 == 1'd1))) begin
            k_buf_0_val_4_d1 = k_buf_0_val_3_q0;
        end else if (((icmp_ln899_reg_783 == 1'd0) & (icmp_ln879_reg_788 == 1'd1))) begin
            k_buf_0_val_4_d1 = p_src_data_stream_V_dout;
        end else begin
            k_buf_0_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln887_reg_774 == 1'd1) & (icmp_ln899_reg_783 == 1'd1) & (1'd1 == and_ln118_reg_821) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((icmp_ln899_reg_783 == 1'd0) & (icmp_ln879_reg_788 == 1'd1) & (1'd1 == and_ln118_reg_821) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_4_we1 = 1'b1;
    end else begin
        k_buf_0_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_5_ce0 = 1'b1;
    end else begin
        k_buf_0_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln887_reg_774 == 1'd1) & (icmp_ln899_reg_783 == 1'd1) & (1'd1 == and_ln118_reg_821) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((icmp_ln899_reg_783 == 1'd0) & (icmp_ln879_reg_788 == 1'd1) & (1'd1 == and_ln118_reg_821) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_5_ce1 = 1'b1;
    end else begin
        k_buf_0_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_630)) begin
        if (((icmp_ln887_reg_774 == 1'd1) & (icmp_ln899_reg_783 == 1'd1))) begin
            k_buf_0_val_5_d1 = k_buf_0_val_4_q0;
        end else if (((icmp_ln899_reg_783 == 1'd0) & (icmp_ln879_reg_788 == 1'd1))) begin
            k_buf_0_val_5_d1 = p_src_data_stream_V_dout;
        end else begin
            k_buf_0_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln887_reg_774 == 1'd1) & (icmp_ln899_reg_783 == 1'd1) & (1'd1 == and_ln118_reg_821) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((icmp_ln899_reg_783 == 1'd0) & (icmp_ln879_reg_788 == 1'd1) & (1'd1 == and_ln118_reg_821) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_5_we1 = 1'b1;
    end else begin
        k_buf_0_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln512_reg_855_pp0_iter3_reg) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_dst_data_stream_V_blk_n = p_dst_data_stream_V_full_n;
    end else begin
        p_dst_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln512_reg_855_pp0_iter3_reg) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_V_write = 1'b1;
    end else begin
        p_dst_data_stream_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln887_reg_774 == 1'd1) & (icmp_ln899_reg_783 == 1'd1) & (1'd1 == and_ln118_reg_821) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln899_reg_783 == 1'd0) & (1'd1 == and_ln118_reg_821) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_src_data_stream_V_blk_n = p_src_data_stream_V_empty_n;
    end else begin
        p_src_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_predicate_op99_read_state4 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op91_read_state4 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        p_src_data_stream_V_read = 1'b1;
    end else begin
        p_src_data_stream_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln443_fu_246_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln444_fu_324_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone)) & ~((ap_enable_reg_pp0_iter4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)) | ((icmp_ln444_fu_324_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ImagLoc_x_fu_352_p2 = ($signed(7'd127) + $signed(zext_ln444_fu_320_p1));

assign and_ln118_fu_378_p2 = (xor_ln118_fu_366_p2 & icmp_ln118_fu_372_p2);

assign and_ln512_fu_424_p2 = (icmp_ln899_reg_783 & icmp_ln891_fu_346_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((1'd1 == and_ln512_reg_855_pp0_iter3_reg) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op99_read_state4 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op91_read_state4 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((1'd1 == and_ln512_reg_855_pp0_iter3_reg) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op99_read_state4 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op91_read_state4 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((1'd1 == and_ln512_reg_855_pp0_iter3_reg) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op99_read_state4 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op91_read_state4 == 1'b1)))));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op99_read_state4 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op91_read_state4 == 1'b1)));
end

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_pp0_stage0_iter4 = ((1'd1 == and_ln512_reg_855_pp0_iter3_reg) & (p_dst_data_stream_V_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_630 = ((1'd1 == and_ln118_reg_821) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_operation_100 = (ap_predicate_op100_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_65 = (icmp_ln444_fu_324_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_67 = (icmp_ln444_fu_324_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_69 = (icmp_ln444_fu_324_p2 == 1'd0);
end

assign ap_enable_operation_81 = (1'b1 == 1'b1);

assign ap_enable_operation_85 = (1'b1 == 1'b1);

assign ap_enable_operation_88 = (1'b1 == 1'b1);

always @ (*) begin
    ap_enable_operation_92 = (ap_predicate_op92_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_93 = (ap_predicate_op93_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_95 = (ap_predicate_op95_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_97 = (ap_predicate_op97_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_98 = (ap_predicate_op98_store_state4 == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_enable_state3_pp0_iter0_stage0 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_enable_state4_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_predicate_op100_store_state4 = ((icmp_ln887_reg_774 == 1'd1) & (icmp_ln899_reg_783 == 1'd1) & (1'd1 == and_ln118_reg_821));
end

always @ (*) begin
    ap_predicate_op91_read_state4 = ((icmp_ln899_reg_783 == 1'd0) & (1'd1 == and_ln118_reg_821));
end

always @ (*) begin
    ap_predicate_op92_store_state4 = ((icmp_ln899_reg_783 == 1'd0) & (icmp_ln879_reg_788 == 1'd1) & (1'd1 == and_ln118_reg_821));
end

always @ (*) begin
    ap_predicate_op93_store_state4 = ((icmp_ln899_reg_783 == 1'd0) & (icmp_ln879_reg_788 == 1'd1) & (1'd1 == and_ln118_reg_821));
end

always @ (*) begin
    ap_predicate_op95_store_state4 = ((icmp_ln899_reg_783 == 1'd0) & (icmp_ln879_2_reg_792 == 1'd1) & (1'd1 == and_ln118_reg_821));
end

always @ (*) begin
    ap_predicate_op97_store_state4 = ((icmp_ln887_reg_774 == 1'd1) & (icmp_ln899_reg_783 == 1'd1) & (1'd1 == and_ln118_reg_821));
end

always @ (*) begin
    ap_predicate_op98_store_state4 = ((icmp_ln887_reg_774 == 1'd1) & (icmp_ln899_reg_783 == 1'd1) & (1'd1 == and_ln118_reg_821));
end

always @ (*) begin
    ap_predicate_op99_read_state4 = ((icmp_ln887_reg_774 == 1'd1) & (icmp_ln899_reg_783 == 1'd1) & (1'd1 == and_ln118_reg_821));
end

assign col_buf_0_val_0_0_fu_455_p3 = ((or_ln457_reg_830[0:0] === 1'b1) ? k_buf_0_val_3_q0 : tmp_16_fu_443_p5);

assign col_buf_0_val_1_0_fu_474_p3 = ((or_ln457_reg_830[0:0] === 1'b1) ? k_buf_0_val_4_q0 : tmp_17_fu_462_p5);

assign col_buf_0_val_2_0_fu_493_p3 = ((or_ln457_reg_830[0:0] === 1'b1) ? k_buf_0_val_5_q0 : tmp_18_fu_481_p5);

assign i_V_fu_252_p2 = (t_V_reg_224 + 6'd1);

assign icmp_ln118_fu_372_p2 = (($signed(ImagLoc_x_fu_352_p2) < $signed(7'd48)) ? 1'b1 : 1'b0);

assign icmp_ln188_1_fu_571_p2 = ((src_kernel_win_0_va_27_fu_544_p3 > select_ln188_fu_563_p3) ? 1'b1 : 1'b0);

assign icmp_ln188_2_fu_588_p2 = ((src_kernel_win_0_va_21_fu_122 > select_ln188_1_fu_583_p3) ? 1'b1 : 1'b0);

assign icmp_ln188_3_fu_602_p2 = ((src_kernel_win_0_va_20_fu_118 > select_ln188_2_fu_594_p3) ? 1'b1 : 1'b0);

assign icmp_ln188_4_fu_616_p2 = ((src_kernel_win_0_va_26_reg_866 > select_ln188_3_fu_608_p3) ? 1'b1 : 1'b0);

assign icmp_ln188_5_fu_658_p2 = ((src_kernel_win_0_va_19_fu_114 > select_ln188_4_reg_889) ? 1'b1 : 1'b0);

assign icmp_ln188_6_fu_670_p2 = ((src_kernel_win_0_va_fu_110 > select_ln188_5_fu_663_p3) ? 1'b1 : 1'b0);

assign icmp_ln188_7_fu_684_p2 = ((col_buf_0_val_0_0_reg_859_pp0_iter2_reg > select_ln188_6_fu_676_p3) ? 1'b1 : 1'b0);

assign icmp_ln188_fu_557_p2 = ((ap_sig_allocacmp_src_kernel_win_0_va_32 > ap_sig_allocacmp_src_kernel_win_0_va_33) ? 1'b1 : 1'b0);

assign icmp_ln443_fu_246_p2 = ((t_V_reg_224 == 6'd50) ? 1'b1 : 1'b0);

assign icmp_ln444_fu_324_p2 = ((t_V_5_reg_235 == 6'd50) ? 1'b1 : 1'b0);

assign icmp_ln879_2_fu_292_p2 = ((t_V_reg_224 == 6'd1) ? 1'b1 : 1'b0);

assign icmp_ln879_fu_286_p2 = ((t_V_reg_224 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln887_fu_258_p2 = ((t_V_reg_224 < 6'd48) ? 1'b1 : 1'b0);

assign icmp_ln891_fu_346_p2 = ((tmp_146_fu_336_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln899_2_fu_298_p2 = ((t_V_reg_224 > 6'd48) ? 1'b1 : 1'b0);

assign icmp_ln899_fu_280_p2 = ((tmp_fu_270_p4 != 5'd0) ? 1'b1 : 1'b0);

assign j_V_fu_330_p2 = (t_V_5_reg_235 + 6'd1);

assign k_buf_0_val_3_address0 = zext_ln835_fu_417_p1;

assign k_buf_0_val_3_address1 = k_buf_0_val_3_addr_reg_837;

assign k_buf_0_val_4_address0 = zext_ln835_fu_417_p1;

assign k_buf_0_val_4_address1 = k_buf_0_val_4_addr_reg_843;

assign k_buf_0_val_5_address0 = zext_ln835_fu_417_p1;

assign k_buf_0_val_5_address1 = k_buf_0_val_5_addr_reg_849;

assign or_ln457_fu_412_p2 = (xor_ln457_reg_778 | icmp_ln118_fu_372_p2);

assign p_dst_data_stream_V_din = tmp_151_reg_895;

assign select_ln121_fu_392_p3 = ((tmp_148_fu_384_p3[0:0] === 1'b1) ? 7'd0 : 7'd47);

assign select_ln188_1_fu_583_p3 = ((icmp_ln188_1_reg_884[0:0] === 1'b1) ? src_kernel_win_0_va_27_reg_873 : select_ln188_reg_879);

assign select_ln188_2_fu_594_p3 = ((icmp_ln188_2_fu_588_p2[0:0] === 1'b1) ? src_kernel_win_0_va_21_fu_122 : select_ln188_1_fu_583_p3);

assign select_ln188_3_fu_608_p3 = ((icmp_ln188_3_fu_602_p2[0:0] === 1'b1) ? src_kernel_win_0_va_20_fu_118 : select_ln188_2_fu_594_p3);

assign select_ln188_4_fu_621_p3 = ((icmp_ln188_4_fu_616_p2[0:0] === 1'b1) ? src_kernel_win_0_va_26_reg_866 : select_ln188_3_fu_608_p3);

assign select_ln188_5_fu_663_p3 = ((icmp_ln188_5_fu_658_p2[0:0] === 1'b1) ? src_kernel_win_0_va_19_fu_114 : select_ln188_4_reg_889);

assign select_ln188_6_fu_676_p3 = ((icmp_ln188_6_fu_670_p2[0:0] === 1'b1) ? src_kernel_win_0_va_fu_110 : select_ln188_5_fu_663_p3);

assign select_ln188_fu_563_p3 = ((icmp_ln188_fu_557_p2[0:0] === 1'b1) ? ap_sig_allocacmp_src_kernel_win_0_va_32 : ap_sig_allocacmp_src_kernel_win_0_va_33);

assign src_kernel_win_0_va_26_fu_526_p3 = ((icmp_ln899_2_reg_796[0:0] === 1'b1) ? tmp_19_fu_515_p5 : col_buf_0_val_1_0_fu_474_p3);

assign src_kernel_win_0_va_27_fu_544_p3 = ((icmp_ln899_2_reg_796[0:0] === 1'b1) ? tmp_20_fu_533_p5 : col_buf_0_val_2_0_fu_493_p3);

assign sub_ln493_fu_314_p2 = ($signed(2'd2) - $signed(trunc_ln506_fu_304_p1));

assign tmp_146_fu_336_p4 = {{t_V_5_reg_235[5:1]}};

assign tmp_147_fu_358_p3 = ImagLoc_x_fu_352_p2[32'd6];

assign tmp_148_fu_384_p3 = ImagLoc_x_fu_352_p2[32'd6];

assign tmp_151_fu_689_p3 = ((icmp_ln188_7_fu_684_p2[0:0] === 1'b1) ? col_buf_0_val_0_0_reg_859_pp0_iter2_reg : select_ln188_6_fu_676_p3);

assign tmp_fu_270_p4 = {{t_V_reg_224[5:1]}};

assign trunc_ln458_fu_408_p1 = x_fu_400_p3[1:0];

assign trunc_ln506_fu_304_p1 = t_V_reg_224[1:0];

assign x_fu_400_p3 = ((and_ln118_fu_378_p2[0:0] === 1'b1) ? ImagLoc_x_fu_352_p2 : select_ln121_fu_392_p3);

assign xor_ln118_fu_366_p2 = (tmp_147_fu_358_p3 ^ 1'd1);

assign xor_ln457_fu_264_p2 = (icmp_ln887_fu_258_p2 ^ 1'd1);

assign xor_ln493_2_fu_438_p2 = (trunc_ln458_reg_825 ^ 2'd3);

assign xor_ln493_fu_308_p2 = (trunc_ln506_fu_304_p1 ^ 2'd1);

assign zext_ln444_fu_320_p1 = t_V_5_reg_235;

assign zext_ln835_fu_417_p1 = x_fu_400_p3;

endmodule //Dilate_0_0_48_48_s
