// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module skin_filter_48x48 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        src_data_stream_0_V_dout,
        src_data_stream_0_V_empty_n,
        src_data_stream_0_V_read,
        src_data_stream_1_V_dout,
        src_data_stream_1_V_empty_n,
        src_data_stream_1_V_read,
        src_data_stream_2_V_dout,
        src_data_stream_2_V_empty_n,
        src_data_stream_2_V_read,
        dst_data_stream_V_din,
        dst_data_stream_V_full_n,
        dst_data_stream_V_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state8 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [7:0] src_data_stream_0_V_dout;
input   src_data_stream_0_V_empty_n;
output   src_data_stream_0_V_read;
input  [7:0] src_data_stream_1_V_dout;
input   src_data_stream_1_V_empty_n;
output   src_data_stream_1_V_read;
input  [7:0] src_data_stream_2_V_dout;
input   src_data_stream_2_V_empty_n;
output   src_data_stream_2_V_read;
output  [7:0] dst_data_stream_V_din;
input   dst_data_stream_V_full_n;
output   dst_data_stream_V_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg src_data_stream_0_V_read;
reg src_data_stream_1_V_read;
reg src_data_stream_2_V_read;
reg dst_data_stream_V_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    src_data_stream_0_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln49_reg_504;
reg    src_data_stream_1_V_blk_n;
reg    src_data_stream_2_V_blk_n;
reg    dst_data_stream_V_blk_n;
reg    ap_enable_reg_pp0_iter5;
reg   [0:0] icmp_ln49_reg_504_pp0_iter4_reg;
reg   [11:0] indvar_flatten_reg_173;
wire   [0:0] icmp_ln49_fu_184_p2;
wire    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
wire    ap_block_state6_pp0_stage0_iter4;
reg    ap_block_state7_pp0_stage0_iter5;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln49_reg_504_pp0_iter1_reg;
reg   [0:0] icmp_ln49_reg_504_pp0_iter2_reg;
reg   [0:0] icmp_ln49_reg_504_pp0_iter3_reg;
wire   [11:0] add_ln49_fu_190_p2;
reg    ap_enable_reg_pp0_iter0;
reg   [7:0] tmp_10_reg_513;
reg   [7:0] tmp_12_reg_519;
wire   [17:0] zext_ln69_2_fu_196_p1;
reg   [17:0] zext_ln69_2_reg_525;
wire   [17:0] mul_ln71_1_fu_200_p2;
reg   [17:0] mul_ln71_1_reg_530;
wire   [17:0] mul_ln73_1_fu_206_p2;
reg   [17:0] mul_ln73_1_reg_535;
wire   [17:0] zext_ln69_1_fu_215_p1;
reg   [17:0] zext_ln69_1_reg_540;
wire   [17:0] mul_ln69_1_fu_432_p2;
reg   [17:0] mul_ln69_1_reg_545;
wire   [15:0] zext_ln69_4_fu_221_p1;
reg   [15:0] zext_ln69_4_reg_550;
wire  signed [17:0] grp_fu_444_p3;
reg  signed [17:0] add_ln71_1_reg_555;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] tmp_reg_561;
reg   [0:0] tmp_reg_561_pp0_iter3_reg;
wire  signed [17:0] grp_fu_453_p3;
reg  signed [17:0] add_ln73_1_reg_567;
reg   [0:0] tmp_6_reg_572;
reg   [0:0] tmp_6_reg_572_pp0_iter3_reg;
wire   [17:0] grp_fu_469_p3;
reg   [17:0] add_ln69_1_reg_578;
reg    ap_enable_reg_pp0_iter3;
wire   [35:0] trunc_ln71_fu_241_p1;
reg   [35:0] trunc_ln71_reg_583;
reg   [9:0] tmp_2_reg_588;
wire   [35:0] trunc_ln73_fu_256_p1;
reg   [35:0] trunc_ln73_reg_593;
reg   [9:0] tmp_8_reg_598;
wire   [0:0] icmp_ln77_3_fu_268_p2;
reg   [0:0] icmp_ln77_3_reg_603;
reg   [0:0] icmp_ln77_3_reg_603_pp0_iter4_reg;
wire   [37:0] mul_ln69_3_fu_498_p2;
reg   [37:0] mul_ln69_3_reg_608;
wire   [0:0] icmp_ln77_fu_382_p2;
reg   [0:0] icmp_ln77_reg_613;
wire   [0:0] icmp_ln77_1_fu_388_p2;
reg   [0:0] icmp_ln77_1_reg_618;
wire   [0:0] icmp_ln77_2_fu_394_p2;
reg   [0:0] icmp_ln77_2_reg_623;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter4;
reg    ap_block_pp0_stage0_01001;
wire   [7:0] mul_ln71_1_fu_200_p1;
wire   [7:0] mul_ln73_1_fu_206_p1;
wire  signed [37:0] mul_ln71_3_fu_482_p2;
wire  signed [37:0] mul_ln73_3_fu_490_p2;
wire   [35:0] sub_ln71_fu_276_p2;
wire   [7:0] tmp_1_fu_281_p4;
wire  signed [18:0] sext_ln71_2_fu_291_p1;
wire  signed [18:0] sext_ln71_3_fu_295_p1;
wire   [18:0] select_ln71_fu_298_p3;
wire   [7:0] trunc_ln71_1_fu_305_p1;
wire   [7:0] sub_ln71_1_fu_309_p2;
wire   [7:0] trunc_ln71_2_fu_315_p1;
wire   [35:0] sub_ln73_fu_326_p2;
wire   [7:0] tmp_7_fu_331_p4;
wire  signed [18:0] sext_ln73_2_fu_341_p1;
wire  signed [18:0] sext_ln73_3_fu_345_p1;
wire   [18:0] select_ln73_fu_348_p3;
wire   [7:0] trunc_ln73_1_fu_355_p1;
wire   [7:0] sub_ln73_1_fu_359_p2;
wire   [7:0] trunc_ln73_2_fu_365_p1;
wire   [7:0] select_ln73_1_fu_369_p3;
wire   [7:0] cr_fu_376_p2;
wire   [7:0] select_ln71_1_fu_319_p3;
wire   [0:0] and_ln77_1_fu_404_p2;
wire   [0:0] and_ln77_fu_400_p2;
wire   [0:0] and_ln77_2_fu_408_p2;
wire   [7:0] trunc_ln_fu_414_p4;
wire   [10:0] mul_ln69_1_fu_432_p0;
wire   [7:0] mul_ln69_1_fu_432_p1;
wire  signed [8:0] grp_fu_437_p0;
wire   [7:0] grp_fu_437_p1;
wire   [9:0] grp_fu_444_p0;
wire   [7:0] grp_fu_444_p1;
wire  signed [17:0] grp_fu_437_p3;
wire   [9:0] grp_fu_453_p0;
wire   [7:0] grp_fu_453_p1;
wire  signed [17:0] grp_fu_461_p3;
wire  signed [7:0] grp_fu_461_p0;
wire   [7:0] grp_fu_461_p1;
wire   [9:0] grp_fu_469_p0;
wire   [7:0] grp_fu_469_p1;
wire   [17:0] grp_fu_475_p3;
wire   [7:0] grp_fu_475_p0;
wire   [7:0] grp_fu_475_p1;
wire   [19:0] mul_ln71_3_fu_482_p0;
wire   [19:0] mul_ln73_3_fu_490_p0;
wire   [19:0] mul_ln69_3_fu_498_p0;
wire   [17:0] mul_ln69_3_fu_498_p1;
wire    ap_CS_fsm_state8;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [16:0] grp_fu_437_p10;
wire   [17:0] grp_fu_444_p10;
wire   [17:0] grp_fu_453_p10;
wire   [15:0] grp_fu_461_p10;
wire   [37:0] mul_ln69_3_fu_498_p10;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
end

skin_process_accekbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 18 ))
skin_process_accekbM_U62(
    .din0(mul_ln69_1_fu_432_p0),
    .din1(mul_ln69_1_fu_432_p1),
    .dout(mul_ln69_1_fu_432_p2)
);

skin_process_accelbW #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
skin_process_accelbW_U63(
    .din0(grp_fu_437_p0),
    .din1(grp_fu_437_p1),
    .din2(mul_ln71_1_reg_530),
    .dout(grp_fu_437_p3)
);

skin_process_accemb6 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
skin_process_accemb6_U64(
    .din0(grp_fu_444_p0),
    .din1(grp_fu_444_p1),
    .din2(grp_fu_437_p3),
    .dout(grp_fu_444_p3)
);

skin_process_accemb6 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
skin_process_accemb6_U65(
    .din0(grp_fu_453_p0),
    .din1(grp_fu_453_p1),
    .din2(grp_fu_461_p3),
    .dout(grp_fu_453_p3)
);

skin_process_accencg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
skin_process_accencg_U66(
    .din0(grp_fu_461_p0),
    .din1(grp_fu_461_p1),
    .din2(mul_ln73_1_reg_535),
    .dout(grp_fu_461_p3)
);

skin_process_acceocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
skin_process_acceocq_U67(
    .din0(grp_fu_469_p0),
    .din1(grp_fu_469_p1),
    .din2(grp_fu_475_p3),
    .dout(grp_fu_469_p3)
);

skin_process_accepcA #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
skin_process_accepcA_U68(
    .din0(grp_fu_475_p0),
    .din1(grp_fu_475_p1),
    .din2(mul_ln69_1_reg_545),
    .dout(grp_fu_475_p3)
);

skin_process_acceqcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 38 ))
skin_process_acceqcK_U69(
    .din0(mul_ln71_3_fu_482_p0),
    .din1(add_ln71_1_reg_555),
    .dout(mul_ln71_3_fu_482_p2)
);

skin_process_acceqcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 38 ))
skin_process_acceqcK_U70(
    .din0(mul_ln73_3_fu_490_p0),
    .din1(add_ln73_1_reg_567),
    .dout(mul_ln73_3_fu_490_p2)
);

skin_process_accercU #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 38 ))
skin_process_accercU_U71(
    .din0(mul_ln69_3_fu_498_p0),
    .din1(mul_ln69_3_fu_498_p1),
    .dout(mul_ln69_3_fu_498_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state8)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln49_fu_184_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indvar_flatten_reg_173 <= add_ln49_fu_190_p2;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_reg_173 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln49_reg_504_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln69_1_reg_578 <= grp_fu_469_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln49_reg_504_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln71_1_reg_555 <= grp_fu_444_p3;
        add_ln73_1_reg_567 <= grp_fu_453_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln49_reg_504 <= icmp_ln49_fu_184_p2;
        icmp_ln49_reg_504_pp0_iter1_reg <= icmp_ln49_reg_504;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln49_reg_504_pp0_iter2_reg <= icmp_ln49_reg_504_pp0_iter1_reg;
        icmp_ln49_reg_504_pp0_iter3_reg <= icmp_ln49_reg_504_pp0_iter2_reg;
        icmp_ln49_reg_504_pp0_iter4_reg <= icmp_ln49_reg_504_pp0_iter3_reg;
        icmp_ln77_3_reg_603_pp0_iter4_reg <= icmp_ln77_3_reg_603;
        tmp_6_reg_572_pp0_iter3_reg <= tmp_6_reg_572;
        tmp_reg_561_pp0_iter3_reg <= tmp_reg_561;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln49_reg_504_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln77_1_reg_618 <= icmp_ln77_1_fu_388_p2;
        icmp_ln77_2_reg_623 <= icmp_ln77_2_fu_394_p2;
        icmp_ln77_reg_613 <= icmp_ln77_fu_382_p2;
        mul_ln69_3_reg_608 <= mul_ln69_3_fu_498_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln49_reg_504_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln77_3_reg_603 <= icmp_ln77_3_fu_268_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln49_reg_504_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        mul_ln69_1_reg_545 <= mul_ln69_1_fu_432_p2;
        tmp_6_reg_572 <= grp_fu_453_p3[32'd17];
        tmp_reg_561 <= grp_fu_444_p3[32'd17];
        zext_ln69_1_reg_540[7 : 0] <= zext_ln69_1_fu_215_p1[7 : 0];
        zext_ln69_4_reg_550[7 : 0] <= zext_ln69_4_fu_221_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln49_reg_504 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        mul_ln71_1_reg_530 <= mul_ln71_1_fu_200_p2;
        mul_ln73_1_reg_535 <= mul_ln73_1_fu_206_p2;
        tmp_10_reg_513 <= src_data_stream_0_V_dout;
        tmp_12_reg_519 <= src_data_stream_2_V_dout;
        zext_ln69_2_reg_525[7 : 0] <= zext_ln69_2_fu_196_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_reg_561 == 1'd0) & (icmp_ln49_reg_504_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_2_reg_588 <= {{mul_ln71_3_fu_482_p2[37:28]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_6_reg_572 == 1'd0) & (icmp_ln49_reg_504_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_8_reg_598 <= {{mul_ln73_3_fu_490_p2[37:28]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln49_reg_504_pp0_iter2_reg == 1'd0) & (tmp_reg_561 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        trunc_ln71_reg_583 <= trunc_ln71_fu_241_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln49_reg_504_pp0_iter2_reg == 1'd0) & (tmp_6_reg_572 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        trunc_ln73_reg_593 <= trunc_ln73_fu_256_p1;
    end
end

always @ (*) begin
    if ((icmp_ln49_fu_184_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln49_reg_504_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        dst_data_stream_V_blk_n = dst_data_stream_V_full_n;
    end else begin
        dst_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln49_reg_504_pp0_iter4_reg == 1'd0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        dst_data_stream_V_write = 1'b1;
    end else begin
        dst_data_stream_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((icmp_ln49_reg_504 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        src_data_stream_0_V_blk_n = src_data_stream_0_V_empty_n;
    end else begin
        src_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln49_reg_504 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_data_stream_0_V_read = 1'b1;
    end else begin
        src_data_stream_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln49_reg_504 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        src_data_stream_1_V_blk_n = src_data_stream_1_V_empty_n;
    end else begin
        src_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln49_reg_504 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_data_stream_1_V_read = 1'b1;
    end else begin
        src_data_stream_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln49_reg_504 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        src_data_stream_2_V_blk_n = src_data_stream_2_V_empty_n;
    end else begin
        src_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln49_reg_504 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_data_stream_2_V_read = 1'b1;
    end else begin
        src_data_stream_2_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln49_fu_184_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((icmp_ln49_fu_184_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln49_fu_190_p2 = (indvar_flatten_reg_173 + 12'd1);

assign and_ln77_1_fu_404_p2 = (icmp_ln77_3_reg_603_pp0_iter4_reg & icmp_ln77_2_reg_623);

assign and_ln77_2_fu_408_p2 = (and_ln77_fu_400_p2 & and_ln77_1_fu_404_p2);

assign and_ln77_fu_400_p2 = (icmp_ln77_reg_613 & icmp_ln77_1_reg_618);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((icmp_ln49_reg_504_pp0_iter4_reg == 1'd0) & (dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln49_reg_504 == 1'd0) & (src_data_stream_2_V_empty_n == 1'b0)) | ((icmp_ln49_reg_504 == 1'd0) & (src_data_stream_1_V_empty_n == 1'b0)) | ((icmp_ln49_reg_504 == 1'd0) & (src_data_stream_0_V_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((icmp_ln49_reg_504_pp0_iter4_reg == 1'd0) & (dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln49_reg_504 == 1'd0) & (src_data_stream_2_V_empty_n == 1'b0)) | ((icmp_ln49_reg_504 == 1'd0) & (src_data_stream_1_V_empty_n == 1'b0)) | ((icmp_ln49_reg_504 == 1'd0) & (src_data_stream_0_V_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((icmp_ln49_reg_504_pp0_iter4_reg == 1'd0) & (dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln49_reg_504 == 1'd0) & (src_data_stream_2_V_empty_n == 1'b0)) | ((icmp_ln49_reg_504 == 1'd0) & (src_data_stream_1_V_empty_n == 1'b0)) | ((icmp_ln49_reg_504 == 1'd0) & (src_data_stream_0_V_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (((icmp_ln49_reg_504 == 1'd0) & (src_data_stream_2_V_empty_n == 1'b0)) | ((icmp_ln49_reg_504 == 1'd0) & (src_data_stream_1_V_empty_n == 1'b0)) | ((icmp_ln49_reg_504 == 1'd0) & (src_data_stream_0_V_empty_n == 1'b0)));
end

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_pp0_stage0_iter5 = ((icmp_ln49_reg_504_pp0_iter4_reg == 1'd0) & (dst_data_stream_V_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign cr_fu_376_p2 = (select_ln73_1_fu_369_p3 ^ 8'd128);

assign dst_data_stream_V_din = ((and_ln77_2_fu_408_p2[0:0] === 1'b1) ? trunc_ln_fu_414_p4 : 8'd0);

assign grp_fu_437_p0 = 17'd130903;

assign grp_fu_437_p1 = grp_fu_437_p10;

assign grp_fu_437_p10 = tmp_12_reg_519;

assign grp_fu_444_p0 = 18'd500;

assign grp_fu_444_p1 = grp_fu_444_p10;

assign grp_fu_444_p10 = tmp_10_reg_513;

assign grp_fu_453_p0 = 18'd500;

assign grp_fu_453_p1 = grp_fu_453_p10;

assign grp_fu_453_p10 = tmp_12_reg_519;

assign grp_fu_461_p0 = 16'd65455;

assign grp_fu_461_p1 = grp_fu_461_p10;

assign grp_fu_461_p10 = tmp_10_reg_513;

assign grp_fu_469_p0 = 18'd299;

assign grp_fu_469_p1 = zext_ln69_1_reg_540;

assign grp_fu_475_p0 = 16'd114;

assign grp_fu_475_p1 = zext_ln69_4_reg_550;

assign icmp_ln49_fu_184_p2 = ((indvar_flatten_reg_173 == 12'd2304) ? 1'b1 : 1'b0);

assign icmp_ln77_1_fu_388_p2 = ((cr_fu_376_p2 < 8'd174) ? 1'b1 : 1'b0);

assign icmp_ln77_2_fu_394_p2 = (($signed(select_ln71_1_fu_319_p3) > $signed(8'd204)) ? 1'b1 : 1'b0);

assign icmp_ln77_3_fu_268_p2 = (($signed(add_ln71_1_reg_555) < $signed(18'd261145)) ? 1'b1 : 1'b0);

assign icmp_ln77_fu_382_p2 = ((cr_fu_376_p2 > 8'd132) ? 1'b1 : 1'b0);

assign mul_ln69_1_fu_432_p0 = 18'd587;

assign mul_ln69_1_fu_432_p1 = zext_ln69_2_reg_525;

assign mul_ln69_3_fu_498_p0 = 38'd268436;

assign mul_ln69_3_fu_498_p1 = mul_ln69_3_fu_498_p10;

assign mul_ln69_3_fu_498_p10 = add_ln69_1_reg_578;

assign mul_ln71_1_fu_200_p1 = zext_ln69_2_fu_196_p1;

assign mul_ln71_1_fu_200_p2 = ($signed(18'd261813) * $signed({{1'b0}, {mul_ln71_1_fu_200_p1}}));

assign mul_ln71_3_fu_482_p0 = 38'd268436;

assign mul_ln73_1_fu_206_p1 = zext_ln69_2_fu_196_p1;

assign mul_ln73_1_fu_206_p2 = ($signed(18'd261725) * $signed({{1'b0}, {mul_ln73_1_fu_206_p1}}));

assign mul_ln73_3_fu_490_p0 = 38'd268436;

assign select_ln71_1_fu_319_p3 = ((tmp_reg_561_pp0_iter3_reg[0:0] === 1'b1) ? sub_ln71_1_fu_309_p2 : trunc_ln71_2_fu_315_p1);

assign select_ln71_fu_298_p3 = ((tmp_reg_561_pp0_iter3_reg[0:0] === 1'b1) ? sext_ln71_2_fu_291_p1 : sext_ln71_3_fu_295_p1);

assign select_ln73_1_fu_369_p3 = ((tmp_6_reg_572_pp0_iter3_reg[0:0] === 1'b1) ? sub_ln73_1_fu_359_p2 : trunc_ln73_2_fu_365_p1);

assign select_ln73_fu_348_p3 = ((tmp_6_reg_572_pp0_iter3_reg[0:0] === 1'b1) ? sext_ln73_2_fu_341_p1 : sext_ln73_3_fu_345_p1);

assign sext_ln71_2_fu_291_p1 = $signed(tmp_1_fu_281_p4);

assign sext_ln71_3_fu_295_p1 = $signed(tmp_2_reg_588);

assign sext_ln73_2_fu_341_p1 = $signed(tmp_7_fu_331_p4);

assign sext_ln73_3_fu_345_p1 = $signed(tmp_8_reg_598);

assign start_out = real_start;

assign sub_ln71_1_fu_309_p2 = (8'd0 - trunc_ln71_1_fu_305_p1);

assign sub_ln71_fu_276_p2 = (36'd0 - trunc_ln71_reg_583);

assign sub_ln73_1_fu_359_p2 = (8'd0 - trunc_ln73_1_fu_355_p1);

assign sub_ln73_fu_326_p2 = (36'd0 - trunc_ln73_reg_593);

assign tmp_1_fu_281_p4 = {{sub_ln71_fu_276_p2[35:28]}};

assign tmp_7_fu_331_p4 = {{sub_ln73_fu_326_p2[35:28]}};

assign trunc_ln71_1_fu_305_p1 = select_ln71_fu_298_p3[7:0];

assign trunc_ln71_2_fu_315_p1 = select_ln71_fu_298_p3[7:0];

assign trunc_ln71_fu_241_p1 = mul_ln71_3_fu_482_p2[35:0];

assign trunc_ln73_1_fu_355_p1 = select_ln73_fu_348_p3[7:0];

assign trunc_ln73_2_fu_365_p1 = select_ln73_fu_348_p3[7:0];

assign trunc_ln73_fu_256_p1 = mul_ln73_3_fu_490_p2[35:0];

assign trunc_ln_fu_414_p4 = {{mul_ln69_3_reg_608[35:28]}};

assign zext_ln69_1_fu_215_p1 = tmp_12_reg_519;

assign zext_ln69_2_fu_196_p1 = src_data_stream_1_V_dout;

assign zext_ln69_4_fu_221_p1 = tmp_10_reg_513;

always @ (posedge ap_clk) begin
    zext_ln69_2_reg_525[17:8] <= 10'b0000000000;
    zext_ln69_1_reg_540[17:8] <= 10'b0000000000;
    zext_ln69_4_reg_550[15:8] <= 8'b00000000;
end

endmodule //skin_filter_48x48
