set_property IOSTANDARD LVCMOS33 [get_ports clk_in1_0]
set_property IOSTANDARD LVCMOS33 [get_ports SWCLKTCK_0]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports ext_reset_in_0]
set_property IOSTANDARD LVCMOS33 [get_ports swd_io_0]
set_property PACKAGE_PIN C17 [get_ports swd_io_0]
set_property PACKAGE_PIN C12 [get_ports ext_reset_in_0]
set_property PACKAGE_PIN K15 [get_ports {GPIO_0_tri_o[0]}]
set_property PACKAGE_PIN H17 [get_ports {GPIO_0_tri_o[1]}]
set_property PACKAGE_PIN D18 [get_ports SWCLKTCK_0]
set_property PACKAGE_PIN E3 [get_ports clk_in1_0]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets SWCLKTCK_0_IBUF]

