set_property IOSTANDARD LVCMOS33 [get_ports clk_in1_0]
set_property IOSTANDARD LVCMOS33 [get_ports SWCLKTCK_0]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports ext_reset_in_0]
set_property IOSTANDARD LVCMOS33 [get_ports swd_io_0]
set_property PACKAGE_PIN C17 [get_ports swd_io_0]
set_property PACKAGE_PIN C12 [get_ports ext_reset_in_0]
set_property PACKAGE_PIN K15 [get_ports {GPIO_0_tri_o[0]}]
set_property PACKAGE_PIN H17 [get_ports {GPIO_0_tri_o[1]}]
set_property PACKAGE_PIN D18 [get_ports SWCLKTCK_0]
set_property PACKAGE_PIN E3 [get_ports clk_in1_0]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets -of_objects [get_ports SWCLKTCK_0]]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets -of_objects [get_ports pclk_0]]

# AXI GPIO control/status values are sampled by the VGA pixel clock in vid_result_overlay.
# The first synchronizer stage is intentionally asynchronous.
set_false_path -to [get_pins -hier -regexp {.*vid_result_overlay_0/inst/ctrl_meta_reg(\[[0-9]+\])?/D}]

set_property IOSTANDARD LVCMOS33 [get_ports rx_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx_0]
set_property PACKAGE_PIN H14 [get_ports rx_0]
set_property PACKAGE_PIN G16 [get_ports tx_0]




set_property IOSTANDARD LVCMOS33 [get_ports {vga_b_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r_0[0]}]
set_property PACKAGE_PIN D8 [get_ports {vga_b_0[3]}]
set_property PACKAGE_PIN D7 [get_ports {vga_b_0[2]}]
set_property PACKAGE_PIN C7 [get_ports {vga_b_0[1]}]
set_property PACKAGE_PIN B7 [get_ports {vga_b_0[0]}]
set_property PACKAGE_PIN A6 [get_ports {vga_g_0[3]}]
set_property PACKAGE_PIN B6 [get_ports {vga_g_0[2]}]
set_property PACKAGE_PIN A5 [get_ports {vga_g_0[1]}]
set_property PACKAGE_PIN C6 [get_ports {vga_g_0[0]}]
set_property PACKAGE_PIN A4 [get_ports {vga_r_0[3]}]
set_property PACKAGE_PIN C5 [get_ports {vga_r_0[2]}]
set_property PACKAGE_PIN B4 [get_ports {vga_r_0[1]}]
set_property PACKAGE_PIN A3 [get_ports {vga_r_0[0]}]
set_property PACKAGE_PIN B11 [get_ports vga_hsync_0]
set_property PACKAGE_PIN B12 [get_ports vga_vsync_0]
set_property IOSTANDARD LVCMOS33 [get_ports vga_hsync_0]
set_property IOSTANDARD LVCMOS33 [get_ports vga_vsync_0]


set_property IOSTANDARD LVCMOS33 [get_ports init_calib_complete_0]
set_property PACKAGE_PIN T16 [get_ports init_calib_complete_0]


set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_1_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_1_tri_o[0]}]
set_property PACKAGE_PIN F3 [get_ports {GPIO_1_tri_o[0]}]
set_property PACKAGE_PIN J2 [get_ports {GPIO_1_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_0_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_0_sda_io]
set_property PACKAGE_PIN E7 [get_ports IIC_0_scl_io]
set_property PACKAGE_PIN J3 [get_ports IIC_0_sda_io]
set_property PULLUP true [get_ports IIC_0_scl_io]
set_property PULLUP true [get_ports IIC_0_sda_io]

set_property IOSTANDARD LVCMOS33 [get_ports pclk_0]
set_property PACKAGE_PIN G2 [get_ports pclk_0]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data_0[0]}]
set_property PACKAGE_PIN G1 [get_ports {cam_data_0[7]}]
set_property PACKAGE_PIN G4 [get_ports {cam_data_0[6]}]
set_property PACKAGE_PIN H1 [get_ports {cam_data_0[5]}]
set_property PACKAGE_PIN H2 [get_ports {cam_data_0[4]}]
set_property PACKAGE_PIN H4 [get_ports {cam_data_0[3]}]
set_property PACKAGE_PIN E6 [get_ports {cam_data_0[2]}]
set_property PACKAGE_PIN G6 [get_ports {cam_data_0[1]}]
set_property PACKAGE_PIN J4 [get_ports {cam_data_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports cam_href_0]
set_property IOSTANDARD LVCMOS33 [get_ports cam_vsync_0]
set_property PACKAGE_PIN F6 [get_ports cam_href_0]
set_property PACKAGE_PIN K1 [get_ports cam_vsync_0]

