# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/vivado_project/M3_t/M3_test/M3_test.cache/wt [current_project]
set_property parent.project_path F:/vivado_project/M3_t/M3_test/M3_test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths f:/vivado_project/AT426-r0p1-00rel0-1/AT426-BU-98000-r0p1-00rel0/vivado/Arm_ipi_repository [current_project]
update_ip_catalog
set_property ip_output_repo f:/vivado_project/M3_t/M3_test/M3_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  F:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/new/swdio_tri_buffer.v
  F:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/new/axis_colorbar.v
  F:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/new/rgb888_to_rgb444_vga.v
  F:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/new/ov5640_dvp_to_axis.v
  F:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
}
add_files F:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_CORTEXM3_AXI_0_0/design_1_CORTEXM3_AXI_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_1/design_1_proc_sys_reset_0_1_board.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_1/design_1_proc_sys_reset_0_1.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_2/design_1_proc_sys_reset_0_2_board.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_2/design_1_proc_sys_reset_0_2.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_v_tc_0_0/design_1_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_v_axi4s_vid_out_0_0/design_1_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_axi_vdma_0_0/design_1_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_axi_vdma_0_0/design_1_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_axi_vdma_0_0/design_1_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr0_0.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/bd_48ac_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/bd_48ac_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/bd_48ac_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/bd_48ac_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/bd_48ac_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_18/bd_48ac_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_19/bd_48ac_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_20/bd_48ac_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_21/bd_48ac_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_22/bd_48ac_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/bd_48ac_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_27/bd_48ac_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_28/bd_48ac_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_29/bd_48ac_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_30/bd_48ac_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_31/bd_48ac_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_32/bd_48ac_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_33/bd_48ac_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_34/bd_48ac_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_35/bd_48ac_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_36/bd_48ac_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_3_0/design_1_proc_sys_reset_3_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_3_0/design_1_proc_sys_reset_3_0.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_3_0/design_1_proc_sys_reset_3_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_axi_clock_converter_0_0/design_1_axi_clock_converter_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_axi_clock_converter_0_0/design_1_axi_clock_converter_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_axi_clock_converter_0_0/design_1_axi_clock_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all F:/vivado_project/M3_t/M3_test/M3_test.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/vivado_project/M3_t/M3_test/M3_test.srcs/constrs_1/new/test.xdc
set_property used_in_implementation false [get_files F:/vivado_project/M3_t/M3_test/M3_test.srcs/constrs_1/new/test.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top design_1_wrapper -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
